### ISSUE TITLE
Business Metrics and Dashboards

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#1]
- Polices to limit usage of certain resources
- Metrics to evaluate usage

**Comment by fforootd** [comment]
I think the following policies are needed

- [ ] Limit Org. per Billing Account
- [ ] Limit Users. per Billing Account
- [ ] Limit Projects. per Billing Account

**Comment by fforootd** [comment]
The following metric is important to the pricing model

- [ ] All Active Users overall projects

**Comment by fforootd** [comment]
We can close this, because we defined the pricing without this metrics as basis
