### ISSUE TITLE
OpenID Connect RP Support

### ISSUE THREAD

**Issue by fforootd** [caos/zitadel#10]
We should Provide inbound Federation for OIDC

It would also be great to fix define a list of preconfigured providers which just need a `Client-ID` `Client-Secret`
IMHO these should be:

- Google
- AzureAD
- Github
- Gitlab
- OIDC Generic 

Polices: TBD on which resource these can be applied

**Comment by fgerschwiler** [comment]
### Idp Configuration:
- type: oidc
- name
- clientid
- client secret
- issuer
- scopes
- logo

### LoginPolicy
- Allow Register (default: true)
- Allow External IDP (default: true)
- External IDPs:
  - oidc: google
  - oidc: azure ad
  - ...
