### ISSUE TITLE
AddMachineKeyResponse returns random creationDate on create

### ISSUE THREAD

**Issue by peintnermax** [caos/zitadel#1016]
AddMachineKey returnes random creationDate. SearchMachineKeys returns correct values.

<img width="436" alt="Bildschirmfoto 2020-11-24 um 16 12 33" src="https://user-images.githubusercontent.com/10165752/100112743-e00b0c00-2e6f-11eb-9a20-ee571aebd765.png">

**Comment by adlerhurst** [comment]
It's actually not random its first of January 0001. Fix is in review
