### ISSUE TITLE
Primary Domain scope does not allow any other login

### ISSUE THREAD

**Issue by buehler** [caos/zitadel#1076]
**Describe the bug**
When using the primary domain scope `urn:zitadel:iam:org:domain:primary:XXX`,
the user is correctly forwarded to the zitadel login page. But if - in some point in time -
I have logged in to a user with another domain, I'm not allowed to switch users.

Maybe, I have a `caos.ch` account, but have not yet logged in on a certain machine,
so I should be able - when forwarded to the login page - to log in with the correct
user.

Right now, the following happens:

(I have logged in with my "smartive" account, so this is cached in my browser)
![image](https://user-images.githubusercontent.com/1067213/101365209-cf14be80-38a3-11eb-96d4-a4a9f74efd49.png)

![image](https://user-images.githubusercontent.com/1067213/101365316-f075aa80-38a3-11eb-89a0-02b78a07180b.png)

While it is fine to not allow my smartive account to be logged in to an application that
demands a `caos.ch` primary domain account, I should be able
to switch my account or login to a new one - given that I have one.

**Comment by livio-a** [comment]
@buehler this error message was returned as the view had some missing data (could not find primary domain caos.ch) which has been fixed now
but error handling will have to improved anyway...
you did not set any prompt value (login, select_account, ...) in your request, right?

**Comment by buehler** [comment]
Nope, I just used the default redirection with the scope limited to the given primary domain.
This was tested with the default react-oidc implementation
