### ISSUE TITLE
JWT AccessToken does not contain primary domain

### ISSUE THREAD

**Issue by buehler** [caos/zitadel#1077]
**Describe the bug**
When using the primary domain scope feature, the returned JWT access token
does not contain the claim to the domain. Without this information, any backend
(zitadel-net in my case) cannot validate that the token should be from a specific domain.

**Steps taken**

I logged in with the correct primary domain:
![image](https://user-images.githubusercontent.com/1067213/101366189-eef8b200-38a4-11eb-8e7b-1225fe9dcdcc.png)

The login redirects me to:
![image](https://user-images.githubusercontent.com/1067213/101366215-f7e98380-38a4-11eb-86bb-18ca24bf4e17.png)

After the login, I get an ID Token and an AccessToken.

The ID Token contains:
```json
//...
"urn:zitadel:iam:org:domain:primary:": "smartive.zitadel.ch",
//...
```

_Note that there is a rogue `:` at the end of the claim name_

While the AccessToken does not contain this key (`urn:zitadel:iam:org:domain:primary`).

Therefore, a backend api cannot validate if a user is logged in with the correct credentials.

**Comment by livio-a** [comment]
Test in dev: 
![image](https://user-images.githubusercontent.com/9405495/102093922-01816700-3e22-11eb-88fa-2393584b784f.png)

will deploy to production by the end of this week
