### ISSUE TITLE
[UX] OIDC / OAuth Wizard improvements

### ISSUE THREAD

**Issue by livio-a** [caos/zitadel#1079]
# OIDC Configs

### currently default for most (Code)
ResponseType: Code
GrantType: Authorization Code (+ Refresh Token)
AuthMethod: Basic

### Equivalent alternative (PKCE)
ResponseType: Code
GrantType: Authorization Code (+ Refresh Token)
AuthMethod: None (for PKCE)

### alternative (for technical reasons)
ResponseType: Code
GrantType: Authorization Code (+ Refresh Token)
AuthMethod: Post (if Basic is not possible for technical reasons)

### Theoretically (until OAuth 2.1) possible but not reasonable: Implicit
ResponseType: IDToken Token (or IDToken)
GrantType: Implicit (+ Refresh Token)
AuthMethod: None (for  Implicit)

### Default (PKCE)
ResponseType: Code
GrantType: Authorization Code (+ Refresh Token)
AuthMethod: None (für PKCE)

### Preferred and with OAuth 2.1 mandatory (PKCE)
ResponseType: Code
GrantType: Authorization Code (+ Refresh Token)
AuthMethod: None (for PKCE)

### More or less the default for most (Implicit)
ResponseType: IDToken Token (or IDToken)
GrantType: Implicit (+ Refresh Token)
AuthMethod: None (for  Implicit)

## Service User (Auth0: Machine-to-Machine application)
GrantType: JWT Profile handled in Service User dialog

---

### Default for all: PKCE
ResponseType: Code
GrantType: Authorization Code (+ Refresh Token)
AuthMethod: None

### Alternative for Web
AuthMethod: Basic or if really necessary Post

### Alternative for Native
none

### Alternative for SPA
ResponseType: IDToken Token (or IDToken)
GrantType: Implicit (+ Refresh Token)
(AuthMethod always None)

**Comment by livio-a** [comment]
@juergrinaldi just let me know if you need further info...
@fforootd i believe this proposal matches your opinion... to push PKCE

**Comment by juergrinaldi** [comment]
<img width="1637" alt="oidc-step01@2x" src="https://user-images.githubusercontent.com/48990649/106587500-ff967300-6549-11eb-8b34-d68de5ad10ac.png">
<img width="1637" alt="oidc-step02a@2x" src="https://user-images.githubusercontent.com/48990649/106587504-00c7a000-654a-11eb-8510-fb51cdc6f83a.png">
<img width="1637" alt="oidc-step03a@2x" src="https://user-images.githubusercontent.com/48990649/106587507-00c7a000-654a-11eb-8c8b-14b147b1d985.png">
<img width="1637" alt="oidc-step05@2x" src="https://user-images.githubusercontent.com/48990649/106587510-01603680-654a-11eb-87b3-ea73323e99bc.png">

obsolete
<img width="1637" alt="oidc-step04a@2x" src="https://user-images.githubusercontent.com/48990649/106587508-00c7a000-654a-11eb-8baf-bbc5ccff366e.png">

**Comment by fforootd** [comment]
I really like these mock-ups 👍

**Comment by livio-a** [comment]
unsure about the texts, but made some proposal

## texts propsals for auth settings

Code: Exchange the authorization code for the tokens
PKCE: Use a random hash instead of a static client secret for more security @fforootd better idea?
Post: Not able to send client secret as "Basic Auth"? Send it in the form itself.  / shorter: Send client_id and client_secret as part of the form
Implicit: Get the tokens directly from the authorization endpoint
Private Key JWT: Use a private key to authorize your application (most secure) <- @peintnermax will be available shortly

## combinations

### web (for the moment)

1. PKCE (recommended)
2. Code
3. Post (not recommended)

### web (with private_key_jwt available)

1. Private Key JWT (recommended) <- how should we label this ...
2. PKCE (recommended) <- ... and this?
3. Code
4. Post (not recommended)

### native

PKCE  only, therefore skip this step

### user agent

1. PKCE (recommended)
2. Implicit (not recommended) <- IMHO we should label it as OAuth 2.1 will remove it and it's already best practice to use PKCE now, @fforootd?

**Comment by fforootd** [comment]
@livio-a 

PKCE: Better protect your app against authorization code high jacking.

Implicit: <- yes we can label this as not recommended 😁

**Comment by mffap** [comment]
I would prefer to keep the pop-up. IMO a user is less likely to navigate away when a pop-up is open. Personally, I would expect that behavior based on other, similar implementations.

**Comment by mffap** [comment]
@livio-a maybe "JWT with private key"
 After some searching there seems no consensus, yet this term is already promiently used. Also for me a little clearer.
