### ISSUE TITLE
DB connection errors

### ISSUE THREAD

**Issue by livio-a** [caos/zitadel#1081]
from time to time there one ore more pods have problem connecting to database

![image](https://user-images.githubusercontent.com/9405495/101594298-bd413180-39f1-11eb-96aa-c1af6771ba28.png)

restart of pods solves the problem, but we should find the cause for this

**Comment by adlerhurst** [comment]
Please add logs

**Comment by livio-a** [comment]
has not occurred anymore... @adlerhurst should we close this?

**Comment by adlerhurst** [comment]
As we have changed some settings for connections and on the DB we can close it
