### ISSUE TITLE
[UX] Add Manager / other Organisation / Link

### ISSUE THREAD

**Issue by maennchen** [caos/zitadel#1109]
**Describe the bug**
The link to add a user from another organisation is hidden behind the next input.

**To Reproduce**
1. Go to Organisation details
2. Click `+` in the `Managers Section

**Expected behavior**
No overlap

**Screenshots**
![Screenshot from 2020-12-16 16-36-23](https://user-images.githubusercontent.com/333918/102370165-10e8e780-3fbd-11eb-8a40-78b62d07cd75.png)

**Desktop (please complete the following information):**
 - OS: `Ubuntu 20.04.1 LTS (Focal Fossa)`
 - Browser: `Google Chrome`
 - Version: `87.0.4280.88 (Official Build) (64-bit)`

**Additional context**
None

**Comment by fforootd** [comment]
This was fixed in https://github.com/caos/zitadel/releases/tag/v0.106.3 and should reach production end of this week
