### ISSUE TITLE
testing passwordless

### ISSUE THREAD

**Issue by livio-a** [caos/zitadel#1111]
- [x] wrong button name (#1112)
- [x] no name (#1112)
![image](https://user-images.githubusercontent.com/9405495/102373061-1b58b080-3fc0-11eb-807b-ad85305e7f05.png)
- [x] view handler error (pwless token is in u2f tokens) -> login still with pw (#1112)

**Comment by fforootd** [comment]
When using windows hello the username is no available in the dialog 

![image](https://user-images.githubusercontent.com/9879976/102374930-2f051680-3fc2-11eb-9b5b-5b162a2d7c17.png)
