### ISSUE TITLE
[Admin UX] Explain Management Roles

### ISSUE THREAD

**Issue by maennchen** [caos/zitadel#1114]
**Describe the bug**
There's no description of the management roles either in the Management Console or the documentation.

**Expected behavior**
Explain what each role does. Best in UI & Docs.

**Comment by fforootd** [comment]
👍 we will take care of this

**Comment by fgerschwiler** [comment]
We published a new Part in the manuals section of the docs. An will link this in console later. https://docs.zitadel.ch/docs/manuals/admin-managers
