### ISSUE TITLE
Billing Account / Module

### ISSUE THREAD

**Issue by fforootd** [caos/zitadel#116]
We need the possibility to create billing accounts which manage payment information and subscription infos.

- Billing Account Lifecycle Process
- Billing Account API / GUI

**Comment by mffap** [comment]
Some thoughts for consideration

Zitadel.ch:
- Payment for zitadel.ch should be possible with credit card(s)
- Domicile of the owner might play a role in VAT
- Limit on Webhooks

Zitadel / Orbos (Product)
- Pricing by cluster and tier (ID?)
- Add-ons are charged by cluster

Integration with Bexio: 
- Retry credit card, when issue orrures; after x retry send to manual inkasso
- Make revenues from zitadel.ch visible in Bexio

**Comment by mffap** [comment]
Wir sollten vielleicht schauen, dass wir zumindest für Kunden mit einer jährlichen Rechnung eine Rechnung anbieten können. Die Kosten für Kreditkarte etc. sind schon recht hoch.
