### ISSUE TITLE
Login Design bugs

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#1172]
**Tested with light design**

- [x] When I click on register with username password, it flickers once in the dark design (I think it flickers on change of the process step)
- [x] Google button looks ugly, because icon is not recognizable
- [x] OTP Qr Code Background should be same white as normal background 
![image](https://user-images.githubusercontent.com/38692350/104753936-ed01f880-5758-11eb-8dc6-96d9c1163b0c.png)

**Tested Dark design on IOS**
- [x] Button styling of registration options: 
![image](https://user-images.githubusercontent.com/9405495/104838953-5cddc380-58be-11eb-9d32-45b494964dad.png)
- [x] Button styling of passwordless: 
![image](https://user-images.githubusercontent.com/9405495/104838898-05d7ee80-58be-11eb-9c76-f9aa7f0e4b72.png)
- [x] spacing of link: 
![image](https://user-images.githubusercontent.com/9405495/104838919-31f36f80-58be-11eb-9e61-959e3c5184da.png)
- [ ] OTP QR Code: Invert colors again? @juergrinaldi ?
- [x] Improve whitespacing between QR code, `Secret` title and secret itself
![image](https://user-images.githubusercontent.com/9405495/104838771-58fd7180-58bd-11eb-934a-947141d548c4.png)
- [x] Register Org Username: display of computed loginname should be improved
![image](https://user-images.githubusercontent.com/9405495/105006339-cb459180-5a36-11eb-87a7-b31ed795d5da.png)
- [x] Register Options: alignment of text 
![image](https://user-images.githubusercontent.com/9405495/105008643-cafac580-5a39-11eb-9300-3da9fb590580.png)
- [x] Password reset: 
![image](https://user-images.githubusercontent.com/9405495/105015830-3cd70d00-5a42-11eb-998a-dff8a962a581.png)
- [x] Password reset done: remove cancel and/or fix alignment
![image](https://user-images.githubusercontent.com/9405495/105015622-08635100-5a42-11eb-9d43-5df6f85b72e2.png)

**Comment by juergrinaldi** [comment]
@fgerschwiler yes, I'd go with a high contrast QR on the corresponding background color.
Like this:
![image](https://user-images.githubusercontent.com/48990649/105827841-c34f9980-5fc2-11eb-9a2a-38820a3575da.png)
