### ISSUE TITLE
Verify Domain Process

### ISSUE THREAD

**Issue by fforootd** [caos/zitadel#123]
We should use a process similar as let's encrypt with the ACME specification
-> https://letsencrypt.org/docs/challenge-types/

- [x] DNS Challenge
- [x] HTTP / HTTPS Challenge

- [x] Show in Zitadel Console

**Comment by livio-a** [comment]
@peintnermax GenerateMyOrgDomainValidation will return a `token` and `url`
so there should be an info for the user:
- dns: token (e.g. `dsf42rg21egw`) must be place in a `TXT` Record at the provided `url` (e.g. _zitadel-challenge.caos.ch)
- http: token (e.g. `dsf42rg21egw`) must be placed as file at the provided `url` (e.g. https://caos.ch/.well-known/zitadel-challenge/dsf42rg21egw)
