### ISSUE TITLE
OpenID Connect oidcc-basic-certification

### ISSUE THREAD

**Issue by fforootd** [caos/zitadel#1236]
Goal is to certify ZITADEL for OpenID Connect

First test prompted for some issues primarily with the error handling

[Public link to the test ](https://www.certification.openid.net/plan-detail.html?plan=yFBd9TKZgzOrk&public=true)

**Comment by fforootd** [comment]
FYI @livio-a

**Comment by livio-a** [comment]
OP Basic Certification has been submitted on Thursday (4.11.): https://www.certification.openid.net/plan-detail.html?plan=w3ddtJcy0tpHL&public=true

Feedback should be provided by noon tomorrow. If not I will request a status update from OIDF

**Comment by fforootd** [comment]
@livio-a nice job, looking forward to find ZITADEL with the OIDF Certification list #KUDOS

**Comment by livio-a** [comment]
got a status update (requested one last Friday):
we're 9th in the queue to be checked
should get feedback this week

**Comment by livio-a** [comment]
we are certified 🥳 🎉 

- https://openid.net/certification/#OPs
- https://openid.net/developers/certified/
