### ISSUE TITLE
MFA: new entry on cancel

### ISSUE THREAD

**Issue by mffap** [caos/zitadel#1265]
#
![screenshot-console zitadel ch-2021 02 09-14_08_45](https://user-images.githubusercontent.com/1366906/107368362-c2e5f100-6ae0-11eb-883f-fd3ee5f68fed.gif)
**Describe the bug**
new entry on cancel while adding Passwordless & U2F

**To Reproduce**
see gif

**Expected behavior**
no new entry on cancel

**Screenshots**
see gif

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome

**Comment by vgtom** [comment]
I would like to work on this issue....can someone guide me on dev env setup?

**Comment by fgerschwiler** [comment]
hi @vgtom we have a contribution guide: https://github.com/caos/zitadel/blob/main/CONTRIBUTING.md
in the section build for local development you can finde the linkt to the guide how to setup your local environment: https://github.com/caos/zitadel/blob/main/guides/development.md

Let me know if you need some more information
