### ISSUE TITLE
Support offline-access via refresh token

### ISSUE THREAD

**Issue by buehler** [caos/zitadel#1314]
**Is your feature request related to a problem? Please describe.**
For SPAs as well as mobile (ionic/reactnative/whatever) applications and PWAs in particular,
it should be possible to request a refresh token to guarantee "offline like" experience.

**Describe the solution you'd like**
A scope that also returns a refresh token according to the standard.

**Comment by livio-a** [comment]
for an initial implementation i suppose the following:
- [ ] when scope `offline_access` is requested together with response_type `code`, an additional refresh_token will be issued (https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess)
- [ ] consent is handled implicitly for the moment (will change with consent being implemented)
- [ ] refresh_token will have a max. idle time of 30 days and a max. lifetime of 90 days for the moment (will be configurable on project / application level later on)
- [ ] refresh_token will rotate on each refresh request for the moment (will be configurable on project / application level later on)
- [ ] we will "renew" / return an id_token on each refresh as well with claims according to https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse
- [ ] refresh requests (grant_type=refresh_token) will need authentication for all types except auth_method none (PKCE) where client_id will suffice (https://tools.ietf.org/html/rfc6749#section-6)
- [ ] refresh requests can have equal or a subset of the original scope (https://tools.ietf.org/html/rfc6749#section-6)
- [ ] users will be able to list all current refresh tokens with their scopes, audience, ...
- [ ] users will be able to revoke them individually or all together
- [ ] token revocation (for clients) will be handled in a separate issue

This would mean that a user would not have to login for 90 days in if he uses the app at least once a month.
@buehler and @fforootd would you prefer other time ranges or do you have any remarks or objections?

**Comment by fforootd** [comment]
This params work fine for me with an initial implementation 👍

**Comment by buehler** [comment]
So @livio-a, if I understand correctly:
When using refresh tokens, zitadel will ask me to login each 90 days (similar to what google and others are doing) ?
I guess this parameters work fine since other "big" players do this as well ;-)

One question though: when you state, in a later implementation it will be possible to configure this time range, will it be possible to configure it to be "unlimited"? so as long as a user logs in with a refresh token each month (or that defined time range), is it possible to use the same login as long as needed?

But to answer your specific question: As long as I'm able to use refresh tokens, I'm pretty happy ;-) I think those params work fine.

**Comment by livio-a** [comment]
@buehler I haven't thought much about the possible options yet. So I can't confirm there will be an "unlimited" option, but I think we'll be offering at least one year (or more) as an option.

We'll keep you informed.

**Comment by fforootd** [comment]
I think we could allow something close to `unlimited` as we provide with the `keys` for the `service accounts`.
We could create a expiry a long time in the future 😁

**Comment by fforootd** [comment]
relates to #1728

**Comment by fforootd** [comment]
@livio-a should we keep this open?

**Comment by livio-a** [comment]
has been deployed to zitadel.ch as well
