### ISSUE TITLE
missing attributes from proto changes

### ISSUE THREAD

**Issue by peintnermax** [caos/zitadel#1374]
- [x] Profile is missing preferredLoginName and id
- [x] updateUserGrantRequest is missing roleKeysList
- [x] addUserGrantRequest is missing roleKeysList and projectgrantid
- [x] resendHumanInitialization is missing email
- [x] MultiFactorType missin otp
- [ ] User grants lack type (org, project, project grant)
- [x] Policies are missing isDefault (cannot check if they are custom or not)
- [x] OrgState.ORG_STATE_ACTIVE instead of OrgState.ORG_STATE_ACTIVATE and OrgState.ORG_STATE_INACTIVE instead of OrgState.ORG_STATE_INACTIVATE
- [ ] AddOrgDomainResponse needs to return at least an id for verification (at best the whole domain data) 
- [x] LoginPolicy missing isDefault
- [x] Management AddSecondFactorToLoginPolicyRequest has setSecondFactor instead of setType in Admin Service (consistency)
- [x] Management AddMultiFactorToLoginPolicyRequest has setMultiFactor instead of setType in Admin Service (consistency)
- [x] Why do some responses use metaData and some other details? 
- [x] Why do same requests use setQuery why do some use setMetadata?
- [x] UpdateOrgIDPRequest hast setIdpId, UpdateIDPRequest has setId (consistency)
- [ ] UserGrant still set in mgmt_pb and auth_pb, may occur for some other too
- [ ] rename queries such that the attribute of the submitted value is not of the same name as the query itself (ex from UserGrantQuery.setDisplayName to UserGrantQuery.setDisplayNameQuery) 
- [ ] Membership is missing type (org, project, project grant)
- [x] rename applicationType to appType in oidcconfig (consitency)

**Comment by adlerhurst** [comment]
Profile is missing preferredLoginName and id => is part of user not of its profile, you request it by user_id so you should know the id.

MultiFactorType missin otp => otp is no multi factor, it's a second factor

User grants lack type (org, project, project grant) => it' only project grant or project. if you need the difference between project grant and project we can add that.

AddOrgDomainResponse needs to return at least an id for verification (at best the whole domain data) => which id? the unique identifier is the domain name you sent in the request

Membership is missing type (org, project, project grant) => it's a oneof (see user.proto Membership)

**Comment by peintnermax** [comment]
removeMyMultifactorOTP -> why do we have removeMyMultiFactorOTP then? :D

**Comment by peintnermax** [comment]
- [ ] authservice: removeMyLinkedIDP, mgmtService: removeLinkedIDP instead of removeUserIDP?
