### ISSUE TITLE
frontend problems new-eventstore

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#1436]
Org:
- [x] Add Org with my user as owner not possible if i change on second page, no button available
- [x] Set Primary Domain button should only be available on verified domains (boolean seems inverted in UI)

Project:
- [x] Show Detail of Granted Project not possible
- [x] On global org its not possible to add a project (ORG_PROJECT_CREATOR)

Granted Project:
- [x] ResourceID on Infopanel (right side): show project grant id instead of project id
- [ ] If I am only Project Grant Owner, I dont get Granted Projects in menu

Application:
- [x] App flow doesnt work, App Type is not set correctly
- [x] app changes are not displayed (maybe projectID and appID are swapped)
- [ ] Add development mode toggle in wizzard
- [x] In my opinion deactivate button should look the same as every where else (next to the title)
- [x] On click on deactivate/activate nothing happens
- [x] On App State translation not correct (screenshot below)

LoginPolicy on Org:
- [x] Klick on + Multifactor doesnt make anything
- [x] Klick on + SecondFactor doesnt make anything

Authorizations:
- [ ] Edit User Grant calls GetProjectGrantByID instead of userGrantByID

Personal Information
- [x] Change Email calls Change Phone
- [x] Phone is not formatted with +41...
- [x] Add OTP label should be named add Factor
- [x] Add OTP doesn't work, after clicking add otp nothing happens
- [x] Add U2F doesn't work, nothing happens
- [x] Add Passwordless doesn't work, nothing happens
- [x] On Add Multifactor dialog, request is sent on button klick (OTP, U2F), remove create button

User:
- [x] Add Member Type Project doesnt work, project id missing
- [x] Add Member Type Project Grant doesnt work, grant id missing
- [x] Change Email on User with state initial should request ResendHumanInitialization with new email value
- [x] Create new user for non global org, email should be allowed
- [ ] As Project Owner I cant add a user grant

Human:
- [x] Change Profile doesnt work, display name missing (display name should be editable)

Machine:
- [ ] When creating a machine user, input fields / form a resized when they're valid, but there's no message (https://github.com/caos/zitadel/issues/1436#issuecomment-803565337)
- [x] Change name not possible, field not editable
- [x] Key Expiry Date should not be shown if its default value ()

Members:
- [x] Username is empty --> Change to preferredloginname

**Comment by livio-a** [comment]
https://user-images.githubusercontent.com/9405495/111904186-d2444c80-8a45-11eb-88f4-7d6c217cf436.mov

**Comment by fgerschwiler** [comment]
On App State translation not correct:
![image](https://user-images.githubusercontent.com/38692350/112604002-ffae4300-8e15-11eb-81a9-3a12de627b80.png)
