### ISSUE TITLE
move zitadel to new domain zitadel.dev

### ISSUE THREAD

**Issue by thesephirot** [caos/zitadel#145]
- [x] new variable names. (citadel to zitadel and other renames)
- [x] new certificate (cloudflare instead of lets encrypt)
- [x] separation of base and overlay
- [x] doublecheck separation of config and secret
- [x] cockraochdb upgrade
- [x] flyway upgrade
- [x] Gitops fixed versions in buildplan
- [x] Migrations shall be executed after DB initialize is complete
- [x] point opstools (grafana, argocd) to a central domain
- [x] google idp

**Comment by fforootd** [comment]
i think the central domain could be something like {tool}.{cluster}.infra.zitadel.dev
for example cd.gcp-eu-west6-a.infra.zitadel.dev

**Comment by thesephirot** [comment]
okay, we need to doublecheck certificate depth then (or use let`s encrypt for them)

**Comment by fforootd** [comment]
ah true CF does not support this depth, hm

**Comment by thesephirot** [comment]
I`d prefere a "single CA strategy" to reduce complexity.
but having an exception for the "ops tools" sounds like a compromise to avoid complicated single level domain names that are odd and too long.

**Comment by thesephirot** [comment]
doubleconfig works fine (but doesn't hide our provider and ip).

https://grafana.gcp-eu-west6-b.infra.zitadel.dev/
https://cd.gcp-eu-west6-b.infra.zitadel.dev/

next step, google auth. (admin pw are in gopass though)
