### ISSUE TITLE
Private Labeling

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#1467]
Outpost:
- [ ] Colors and Logo (Register, Login, Console)
- [ ] Dark/Light Model

Starbase
- [ ] Text Customization

Fortress
- [ ] MetaData
- [ ] Register User Fieldset
- [ ] Fonts
- [ ] Disable Powered By Zitadel

**Comment by fforootd** [comment]
We should also track the ability for customers to run the login / register with their own domain.

**Comment by fgerschwiler** [comment]
- [ ] Link for more informations
- [ ] Fonts
- [ ] Customized Error messages
- [ ] User Avatar
- [ ] Show password possiblity

**Comment by fgerschwiler** [comment]
LogoDark asset
PrimaryColorDark string
SecondaryColorDark string
WarnColorDark string

LogoLight
PrimaryColorLight
SecondaryColorLight
WarnColorLight

FontList Different weights

EnablePasswordShow
ShowErrorMessagesAsPopup
