### ISSUE TITLE
ctrl+f / cmd+f is overwritten in docs page

### ISSUE THREAD

**Issue by buehler** [caos/zitadel#1471]
**Describe the bug**
When trying to search through the documentation (https://docs.zitadel.ch/) ctrl+f / cmd+f is overwritten with a pseudo search.
This may be feasible when everything is searched through (like original ctrl+f) but not when no full text search over all content is provided.

**Expected behavior**
When using the search hotkey on an operating system, the default action should be executed and not be overwritten.
I'd suggest to use ctrl(cmd) + shift + f for such a custom search behavior to enable users to search for keywords with the normal browser function.

**Comment by mffap** [comment]
We switched to new docs framework. The described issue should be solved.
