### ISSUE TITLE
When given access to an Org Project, I see the organization

### ISSUE THREAD

**Issue by buehler** [caos/zitadel#1472]
**Describe the bug**
As an example, in the CAOS AG organization, I have access to the project "zitadel-net".
Since I'm somewhat entangled with the organization now, I see the link to view the organization.
But I have no access to view the organization itself, so right now, there is a button which I can click, but actually does nothing.

**Expected behavior**
When I have no access to some resource / view, I expect the navigation link to be in a disabled state or hidden.

**Screenshots**
![image](https://user-images.githubusercontent.com/1067213/112441047-48e59080-8d4b-11eb-8ca5-64fec5e1828b.png)

**Comment by adlerhurst** [comment]
We were not able to reproduce the bug in the current version. Please reopen if needed with further information

**Comment by buehler** [comment]
It still happens :-)
BUT only if you start off with another org.

I just tried. My starting org was "Rootd". When I switched to CAOS AG, the "organization" link was still there. only after I refreshed, the link was gone.

**Comment by fforootd** [comment]
This looks like a frontend issue 😁

**Comment by fforootd** [comment]
any opinion @peintnermax 

it seems like this happens when a user has a management role lower than on the org. level.

**Comment by peintnermax** [comment]
Will be closed with #1688. This is a relic from when we had more functionality behind the /org route. The mr removes regex checks of project.read(:[0-9]*)? , user.read(:[0-9]*)? and user.grant.read(:[0-9]*)? and gives access to users only with permission org.read.

**Comment by livio-a** [comment]
Has been deployed to zitadel.ch
