### ISSUE TITLE
Save the last selected Organization on console.zitadel.ch

### ISSUE THREAD

**Issue by buehler** [caos/zitadel#1503]
**Is your feature request related to a problem? Please describe.**
When logging in into console.zitadel.ch, it should remember my last used organization and select this org by default. Since organizations are ordered by name, I'm always on an org that I rarely need.

**Describe the solution you'd like**
Store the last used organization and select it by default when I log in.

**Additional context**
![image](https://user-images.githubusercontent.com/1067213/113139294-35449900-9227-11eb-8af8-668e09365564.png)

**Comment by fgerschwiler** [comment]
- [ ] Add an attribute on the user with the last organisation

**Comment by livio-a** [comment]
This has been solved a while ago
