### ISSUE TITLE
OIDC Callback Url is not conform to RFC3986

### ISSUE THREAD

**Issue by latonz** [caos/zitadel#1588]
**Describe the bug**
The OIDC authorisation code flow callback url does not conform to [rfc3986](https://tools.ietf.org/html/rfc3986).
For example a callback url used by zitadel can look like this: `https://openidconnect.net/callback?code=c-<some-secret-chars>&state=<state>`. `<some-secret-chars>` looks like base64-encoded bytes incl. padding, but the padding is not encoded correctly (`<some-secret-chars>` often ends with `==` which does not conform to [rfc3986 section2.2](https://tools.ietf.org/html/rfc3986#section-2.2)). There are oidc certified client libraries which cannot handle this (ex. [IdentityModel.OidcClient](https://github.com/IdentityModel/IdentityModel.OidcClient)).

**To Reproduce**
1. Setup a project and an application (native, authorisation code, auth method none) in zitadel
2. Whitelist `https://openidconnect.net/callback` as a callback url
3. Go to [https://openidconnect.net/](https://openidconnect.net/)
4. Click configuration and enter the details provided by zitadel
5. Open the chrome devtools network tab and set the `Preserve log` flag
5. Click START
6. Authenticate using zitadel
7. Check the network logs for a request url starting with `https://openidconnect.net/callback`. This callback url is not conform to RFC3986.

**Expected behavior**
The callback url should conform to RFC3986 and oidc certified client libraries should be able to handle it correctly.

**Additional context**
It could be sufficient to switch from base64 ([rfc4648 section 4](https://tools.ietf.org/html/rfc4648#section-4)) to base64url encoding ([rfc4648 section 5](https://tools.ietf.org/html/rfc4648#section-5)).

**Comment by fforootd** [comment]
Thx for reporting this.

Opinions @livio-a

**Comment by livio-a** [comment]
@latonz thanks for reporting

https://github.com/caos/zitadel/issues/1588 will close this issue

will be deployed to Production tomorrow along with Version 1.0
