### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#1609]
The Identity Providers on the Login Policy shows wrong type
Its the Type oidc or saml not sysem or org.
And the name should be shown.
 
![image](https://user-images.githubusercontent.com/38692350/115191303-88ed2880-a0e9-11eb-84c4-987f7bb2adbf.png)

**Comment by livio-a** [comment]
disable toogles when not allowed:
![image](https://user-images.githubusercontent.com/9405495/115193067-f437fa00-a0eb-11eb-99eb-50a04b31c801.png)

**Comment by livio-a** [comment]
display audit log retention as days or weeks or months instead of hours
![image](https://user-images.githubusercontent.com/9405495/115196467-3a8f5800-a0f0-11eb-9d79-4b7c8738aa87.png)

**Comment by livio-a** [comment]
remove auth factor:
![image](https://user-images.githubusercontent.com/9405495/115197538-6232f000-a0f1-11eb-9493-a461ce602db2.png)

**Comment by livio-a** [comment]
- [ ] don't display section "features" when not allowed (permission org.features.read / write)
- [ ] change text from "...aktivieren sowie deaktivieren / activate or deactivate" to "anzeigen / display"
- [ ] change button text to "featureset anzeigen / display featureset"
- [ ] enable "Preisstufe anpassen" only with permission org.write
