### ISSUE TITLE
Deactivate/Reactivate on newly created user

### ISSUE THREAD

**Issue by adlerhurst** [caos/zitadel#1638]
**Describe the bug**
If i create a new user i can see the deactivate and reactivate button.

**To Reproduce**
1. Create user
2. you can see two buttons on the top right corner 

**Expected behaviour**

There should only be a deactivate button

**Screenshots**

<img width="786" alt="image" src="https://user-images.githubusercontent.com/27845747/115574118-a543bd80-a2c1-11eb-8f60-9f797dd729d5.png">

**Desktop (please complete the following information):**
 - OS: macos big sur
 - Browser safari
 - Version 14.0.3 (16610.4.3.1.7)

**Comment by livio-a** [comment]
This is now deployed on zitadel.ch
