### ISSUE TITLE
manger roles out of window

### ISSUE THREAD

**Issue by adlerhurst** [caos/zitadel#1642]
**Describe the bug**
If a user has many ZITADEL MANAGER ROLES the roles 

**To Reproduce**
1. open a user with many ZITADEL MANAGER ROLES

**Expected behaviour**
I should be able to see all roles

**Screenshots**
<img width="322" alt="image" src="https://user-images.githubusercontent.com/27845747/115579078-1e451400-a2c6-11eb-8120-b9fcf01e0aa6.png">

**Desktop (please complete the following information):**
 - OS: macos big sur
 - Browser safari
 - Version 14.0.3 (16610.4.3.1.7)

**Comment by livio-a** [comment]
This is now deployed on zitadel.ch
