### ISSUE TITLE
Count of users is wrong

### ISSUE THREAD

**Issue by sebastianbuechler** [caos/zitadel#1671]
When applying a filter to the users list the total count on the bottom left gets updated only as long as the filtered list is not empty.

If the filter does not match any of the users, the total count will display the last positive number it had.

![image](https://user-images.githubusercontent.com/42775578/116050750-214e5480-a678-11eb-9f01-55d97792f806.png)

**Comment by fforootd** [comment]
@peintnermax i can confirm that this happens.

Is this frontend related or from the api?

**Comment by peintnermax** [comment]
This is a frontend issue. It will be fixed with #1670

**Comment by livio-a** [comment]
This is now deployed on zitadel.ch
