### ISSUE TITLE
Show warning when trying to delete own user account

### ISSUE THREAD

**Issue by sebastianbuechler** [caos/zitadel#1673]
When deleting a user in the user list via the garbage can icon it is possible to delete the logged-in account without a warning. In this case, a warning with the need for confirmation could prevent some nasty issues afterward.

**Comment by adlerhurst** [comment]
hi @sebastianbuechler 

Thanks for your request. We will schedule it on Wednesday and update the issue.

Kind regards

**Comment by fgerschwiler** [comment]
- [ ] Extend the warning on clicking delete user in the users overview, if its own user

WARNING: This is your own user account, by permanently delete this user you will be logged out.

![image](https://user-images.githubusercontent.com/38692350/148562911-e2a277c7-7e6e-4142-83d2-65f585e39ea4.png)
