### ISSUE TITLE
Allow additional origins on applications

### ISSUE THREAD

**Issue by buehler** [caos/zitadel#1689]
**Is your feature request related to a problem? Please describe.**
When configuring OIDC applications in a project, I want to be able to add additional origins to the allowed origin list, other than the redirect URIs.

This happens - specifically - when using native apps with Ionic / react native and such technologies which run in a local browser on `http://localhost`.

**Describe the solution you'd like**
I'd like to be able to add redirect uris and additional allowed origins for CORS calls such that react native apps may run on localhost on the phone.

**Describe alternatives you've considered**
The development mode 😏

**Additional context**
Error code: `OIDC-da1f3`

**Comment by fgerschwiler** [comment]
hi @buehler 

Thanks for your request. @livio-a will have a look at this

Kind regards

**Comment by livio-a** [comment]
has been deployed to zitadel.ch as well

**Comment by ibnunowshad** [comment]
I need some context about this feature. Even if I come from different origin, the redirect URI still go to redirect URI after authentication. If so, what is the point of this feature?
