### ISSUE TITLE
Password reset in zitadel console does not work properly

### ISSUE THREAD

**Issue by sebastianbuechler** [caos/zitadel#1693]
I tried to reset a password for a different user in the Zitadel Console. After resetting I can log in, but the user needs to reset this newly set password immediately during login, which seems weird. Anyway, if I want to reset this time it does not accept any new password, even if it fulfills all criteria of the password strength.

**Comment by fgerschwiler** [comment]
hi @sebastianbuechler 

Thanks for your bug report.
When an administrator sets a new password for a user we handle this as a initial/one time password, the user is forced to change it on the next login. This has some security reasons, that the admin is not able to use the users account after.

I couldn't reproduce the error you had. Are you sure, that the new passwords were exactly the same?
Could you send us the error you get or some more informations?

Kind regards
