### ISSUE TITLE
Wrong value displayed as minimum length for password rules durin password reset

### ISSUE THREAD

**Issue by sebastianbuechler** [caos/zitadel#1694]
When resetting a password for a user in Zitadel console we can see the rules for a new password displayed. One of them is a minimum length, which should be static. However, at the moment it just counts the actual length of the current password. In the example screenshot, the minimum length would be 8 characters and the current password in the field has a length of 21 characters.

![image](https://user-images.githubusercontent.com/42775578/116671391-2b869080-a9a1-11eb-8f2a-b532effd1e04.png)

**Comment by fgerschwiler** [comment]
hi @sebastianbuechler 

Thanks for your bug report.
@peintnermax will have a look at this

Kind regards

**Comment by peintnermax** [comment]
#1695 fixes the issue
