### ISSUE TITLE
docker-compose failed 

### ISSUE THREAD

**Issue by you1996** [caos/zitadel#1768]
**Describe the bug**
Hi 
I am new to zitadel and i like to test it locally , facing this issue when following those steps [README.md](https://github.com/caos/zitadel/blob/update-contrib/build/README.md) 
Any help please
thank you!
**To Reproduce**
[README.md](https://github.com/caos/zitadel/blob/update-contrib/build/README.md) 
when trying to build the go image to start the container by this docker-compose command
`COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose -f build/docker-compose-dev.yml up --build  go
`
**Expected behavior**

**Screenshots**
![zitadel_issue](https://user-images.githubusercontent.com/45292366/119004245-4b005000-b986-11eb-8b13-c4bc152c1654.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Additional context**

**Comment by fforootd** [comment]
Hi @you1996 👋 

Happy to help. It looks like ZITADEL does get the proper argument to start the container.
I will investigate this and keep you posted.

FYI we are currently working on a documentation for developers who would like to contribute.

@adlerhurst is already working on this.

**Comment by you1996** [comment]
Cool happy to hear about a dev doc
Thank you @fforootd

**Comment by fforootd** [comment]
A WIP is located here https://github.com/caos/zitadel/pull/1754/files

But i think this is not relying on docker compose to build ZITADEL, instead use the locally installed go.
As of today I think most of us use local setups without compose. But we still rely on docker build to generate the GRPC Code.

**Comment by adlerhurst** [comment]
> A WIP is located here https://github.com/caos/zitadel/pull/1754/files
> 
> 
> 
> But i think this is not relying on docker compose to build ZITADEL, instead use the locally installed go.
> 
> As of today I think most of us use local setups without compose. But we still rely on docker build to generate the GRPC Code.
> 
> 
> 
> 

This PR is currently not fixing the problem in the compose file. I will have a look on in today

**Comment by gedw99** [comment]
@fforootd building with pure go is still useful i think. even if the grpc code gen needs docker.

**Comment by fforootd** [comment]
@gedw99 we will keep and document the `native` way for sure!
