### ISSUE TITLE
org search field

### ISSUE THREAD

**Issue by adlerhurst** [caos/zitadel#1784]
**Describe the bug**

If I start typing in the org search field on the top left side each key stroke creates a new search. After the response i cannot continue writing or some key strokes are ignored.

**To Reproduce**

Steps to reproduce the behaviour:

1. ZITADEL
2. start search for an existing org (in the top left corner)
3. type a letter where multiple orgs will be found
4. type more letters and see what you typed after the list reloaded

**Expected behaviour**

All key strokes should end in a typed letter. In my opinion the list is veery nervous would be nice if it would get less nervous

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 14.1 (16611.1.21.161.6)

**Comment by livio-a** [comment]
@peintnermax this is fixed, right?

**Comment by peintnermax** [comment]
there's still some strange behaviour. Observing it 🧐
