### ISSUE TITLE
User registration: Form validation does not show when password confirmation is wrong

### ISSUE THREAD

**Issue by astriffe** [caos/zitadel#1827]
**Describe the bug**
If the user enters different passwords in 'Password' and 'Password confirmation boxes, the 'next' button remains disabled but no form validation warning is shown. This makes it hard for the user to detect what is wrong in the registration form.

**To Reproduce**
1. Go to the registration form
2. Enter all required inputs
3. Type different values in password and password confirmation
4. See that there's no validation warning :)

**Expected behavior**
Any kind of hint (red border?) so I see what is actually wrong with my inputs

**Screenshots**
![image](https://user-images.githubusercontent.com/411980/121038542-ad43b800-c7b0-11eb-95b9-5b6e6118e90c.png)

**Comment by fgerschwiler** [comment]
hi @astriffe 

Thanks for this bug report. We will schedule it on Wednesday and update the issue.

**Comment by you1996** [comment]
Hi @fgerschwiler , i'll be happy if i could contribute by fixing this 😃  !
i'am ready for a PR

**Comment by fgerschwiler** [comment]
Hi @you1996, this would be great. 
Just let us know, if you need any help or further informations from us.

**Comment by you1996** [comment]
Thanks @fgerschwiler, done !
If there is any other related changes that must be done, a hint or a ref to the source-code will be helpful .
