### ISSUE TITLE
Error message on saving font colors

### ISSUE THREAD

**Issue by mffap** [caos/zitadel#1884]
**Describe the bug**
When saving font colors, I get an error message. This seems to appear only shortly after first-time using the private labeling policy.

**To Reproduce**
1. Use an org without label policy
2. Go to https://console.zitadel.ch/org/policy/privatelabel
3. Change Font Colors
4. Click Save on Font Colors
5. Error message should pop up

**Expected behavior**
Successful Save

**Screenshots**
![image](https://user-images.githubusercontent.com/1366906/122344219-d6014580-cf46-11eb-8125-4d1a1583758d.png)

**Additional context**
Seems to have disappeared after some minutes.

**Comment by fgerschwiler** [comment]
This should be fixed a reload was missing
