### ISSUE TITLE
Upload font unclear

### ISSUE THREAD

**Issue by mffap** [caos/zitadel#1888]
**To Implement**
- [ ] Add allowed file formats: otf, ttf
- [ ] On uploading with the select file link, I have to choose my file twice, This doesnt happen when I drop the file

**Describe the bug**
It is unclear in which format the font needs to be uploaded. The UI says "Drop image here", there is no filter on the upload, and the file format is not clear from the documentation.

**To Reproduce**
1. Goto https://console.zitadel.ch/org/policy/privatelabel
2. Click on font
2. Go to https://docs.zitadel.ch/docs/manuals/admin-policies

**Expected behavior**
Clear indication what file formats are allowed.

**Screenshots**
![image](https://user-images.githubusercontent.com/1366906/122352776-b589b900-cf4f-11eb-8d01-ecf90951370c.png)

**Comment by fgerschwiler** [comment]
Estimate: < 0.5d
