### ISSUE TITLE
Error 500 when uploading font

### ISSUE THREAD

**Issue by mffap** [caos/zitadel#1893]
**Describe the bug**
When uploading a ttf file (124kb) to change the font, I get an HTTP 500 Response error pop-up.

**To Reproduce**
1. Go to http://www.911fonts.com/font/download_ComicSansMSRegular_2086.htm or similar to download font as ttf
2. Go to https://console.zitadel.ch/org/policy/privatelabel
2. Click on Font
3. Upload .ttf file

**Expected behavior**
Success

**Screenshots**
![image](https://user-images.githubusercontent.com/1366906/122372684-29808d00-cf61-11eb-944d-d60e374945f9.png)

**Comment by livio-a** [comment]
has been fixed with #1886 and deployed to zitadel.ch
