### ISSUE TITLE
Switch text colors based on background (automatically)

### ISSUE THREAD

**Issue by mffap** [caos/zitadel#1921]
**Is your feature request related to a problem? Please describe.**
Currently, I can set font colors for private labeling. However, when my background is "light" and my primary color is "dark", then visibility of the button text might be low. 

Example:
![image](https://user-images.githubusercontent.com/1366906/122919635-bf048e00-d360-11eb-8ba5-07d0418c5289.png)

**Describe the solution you'd like**
Colors should be adjusted automatically, based on contrast.

**Describe alternatives you've considered**
Optionally, let users pick font colors matching a given color (primary, background).

**Additional context**
An example / explainer on how to switch colors automatically in CSS: https://css-tricks.com/switch-font-color-for-different-backgrounds-with-css/

**Comment by fgerschwiler** [comment]
@mffap i just checked this issue. at this already works as expected.
we do automatically adjust the color based on the contrast. Some colors are just on the boarder so it might look like it is the wrong contrast.

example: 
light color:
![image](https://user-images.githubusercontent.com/38692350/150978432-145e357e-2f69-4a23-9fba-f300385c366b.png)

dark color:
![image](https://user-images.githubusercontent.com/38692350/150978513-474cdf99-9707-48a9-b376-2c79fa773709.png)
