### ISSUE TITLE
Improve Pipeline

### ISSUE THREAD

**Issue by livio-a** [caos/zitadel#1923]
As of now pipelines for PR from forks are running, but there are still improvements to be done:
- [ ] version handling of tools
  - [ ] protoc and stuff
  - [ ] tools/go.mod
- [ ] caching
- [ ] separate pipelines (with dependency to each other)
- [ ] dev releases

@fforootd and @thesephirot if you have more requirements / ideas please add them

**Comment by livio-a** [comment]
@fforootd i think we can close this for now, right?

**Comment by fforootd** [comment]
IMO yes for the moment
