### ISSUE TITLE
Uploading large-size user avatar results in Error 500

### ISSUE THREAD

**Issue by mffap** [caos/zitadel#1927]
**Describe the bug**
If I upload a image with 2.6 MB size, then I receive a HTTP500 Error message from the server. If I upload a image with 250 KB, then the upload is successful.

**To Reproduce**
1. Go to your profile
2. Click on your avatar
3. Upload an image with 2.5 MB (or presumably over 500 KB)

**Expected behavior**
Correct Error category with human readable response, that explains what the user has to do.

**Screenshots**
![image](https://user-images.githubusercontent.com/1366906/123264950-d2e3f780-d4fa-11eb-90db-514c7ceb02d8.png)

**Comment by rojanDinc** [comment]
Could this https://github.com/caos/zitadel/blob/81974b977d932289d3e48c66831e74106f5697d5/internal/api/assets/asset.go#L106 be the max limit for upload file size?

**Comment by livio-a** [comment]
@rojanDinc the line you've mentioned is the maxMemory size (2MB) for the form parsing

the Uploader interface has a MaxFileSize function:
https://github.com/caos/zitadel/blob/81974b977d932289d3e48c66831e74106f5697d5/internal/api/assets/asset.go#L53

which is implemented by the myHumanAvatarUploader struct and value is set here (500KB):
https://github.com/caos/zitadel/blob/c93e3370d28658ee93c1015db89669ae842433e9/internal/api/assets/user_avatar.go#L13

there are two problems now:
- there's a `errorHandler` which is used in the upload functions, e.g. for max size validation:
https://github.com/caos/zitadel/blob/c93e3370d28658ee93c1015db89669ae842433e9/internal/api/assets/asset.go#L130
this error handler is now set to write a HTTP 500 with the error message:
https://github.com/caos/zitadel/blob/c93e3370d28658ee93c1015db89669ae842433e9/internal/api/assets/asset.go#L65
this should be changed to send a correct HTTP Statuscode (and perhaps change the format of the error message)
- console must parse / display the error message

For a better user experience the max file size should also be displayed in console before uploading.
