### ISSUE TITLE
[Performance] GetProjectById Slow

### ISSUE THREAD

**Issue by maennchen** [caos/zitadel#1937]
**Describe the bug**

When loading `GetProjectById` via the console. The request can take up to 10 seconds.

**To Reproduce**
1. Go to https://console.zitadel.ch/projects/86761430715523969
2. See how long it takes to load

**Expected behavior**

A faster response.

**Screenshots**

None

**Additional context**

```console
$ curl 'https://api.zitadel.ch/zitadel.management.v1.ManagementService/GetProjectByID' \
  -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"' \
  -H 'X-User-Agent: grpc-web-javascript/0.1' \
  -H 'Accept-Language: en-US' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'Authorization: Bearer [TOKEN]' \
  -H 'x-zitadel-orgid: 86614223882349580' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36' \
  -H 'X-Grpc-Web: 1' \
  -H 'Referer: ' \
  -H 'Content-Type: application/grpc-web+proto' \
  --data-raw $'\u0000\u0000\u0000\u0000\u0013\n\u001186761430715523969' \
  --compressed
```

**Comment by maennchen** [comment]
Same for, might be connected.

```console
curl 'https://api.zitadel.ch/zitadel.management.v1.ManagementService/ListAppChanges' \
  -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"' \
  -H 'X-User-Agent: grpc-web-javascript/0.1' \
  -H 'Accept-Language: en-US' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'Authorization: Bearer [TOKEN]' \
  -H 'x-zitadel-orgid: 86614223882349580' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36' \
  -H 'X-Grpc-Web: 1' \
  -H 'Referer: ' \
  -H 'Content-Type: application/grpc-web+proto' \
  --data-raw $'\u0000\u0000\u0000\u0000*\n\u0002\u0010\u0014\u0012\u001186761430715523969\u001a\u001187502525980273684' \
  --compressed
```

**Comment by fgerschwiler** [comment]
Hi @maennchen thanks for your report.
We are currently working on the query side optimisation, which should resolve this problem.
The problem we have at the moment, that we are reading all the events of the aggregate, even if they are not interesting for the computed model. And on you project are a lot of events of types that are actually not interesting for the model. (e.g client id check succeeded)
We will inform you as soon as we know when we have fixed this.

**Comment by maennchen** [comment]
@fgerschwiler FYI: `upstream request timeout` now makes the console completely unusable for us.

**Comment by adlerhurst** [comment]
hi @maennchen we found the problem and implemented a fix [here](https://github.com/caos/zitadel/pull/1949).

**Comment by maennchen** [comment]
@adlerhurst The request now takes 8.3s.

**Comment by adlerhurst** [comment]
hi @maennchen the issue is solved on zitadel.ch

**Comment by adlerhurst** [comment]
hi @maennchen we had to rollback the the fix for the activitiy stream as other queries started to slow down. Project by id is still fast.

**Comment by maennchen** [comment]
@adlerhurst / @fgerschwiler The page now loads a lot faster :+1:

**Comment by adlerhurst** [comment]
This call is moved to the newly implemented query side. This change improves the query speed.
