### ISSUE TITLE
Not possible to authorize users

### ISSUE THREAD

**Issue by buehler** [caos/zitadel#1996]
**Describe the bug**
When trying to authorize a user within a project, a "duplication error" occurs.

**To Reproduce**
1. Go to an organization
2. Click on a user without authorizations
3. Try to add an authorization for a project

**Screenshots**
![image](https://user-images.githubusercontent.com/1067213/125068318-a2cd5480-e0b5-11eb-9c3b-69541747a619.png)

**Comment by adlerhurst** [comment]
Hi @buehler thanks for your report. We try to reproduce the bug and give feedback as soon as possible. Enjoy your weekend 😉

**Comment by adlerhurst** [comment]
@buehler 

We fixed the bug and you should be able to authorize your users :)
