### ISSUE TITLE
Email Templates

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#2]
- [x] customized email templates for domains
- [x] render email template
- [ ] GUI

**Comment by juergrinaldi** [comment]
![image](https://user-images.githubusercontent.com/48990649/90748828-f9ca0f80-e2d2-11ea-9695-b3631c66280d.png)

Assets: https://drive.google.com/drive/u/1/folders/1bsj1EqBbN8BR78OLH52iUAG5JlMDtN5K
Font: Lato (like everywhere else)
Background-Colors: #0E1533, #0B1129 // #F2F2F2, #FFFFFF
