### ISSUE TITLE
userinfo attributs missing in id_token when requesting JWT access token with roles

### ISSUE THREAD

**Issue by livio-a** [caos/zitadel#2051]
### Discussed in https://github.com/caos/zitadel/discussions/2050

<div type='discussions-op-text'>

<sup>Originally posted by **astriffe** July 20, 2021</sup>
Hi caos!

Might it be that the preferred email vanished from the token, while the checkbox 'User Info im ID Token' is still set?

Of course I might be wrong, but I can't find the email claim on any of the tokens I receive :)

Cheers, Alex</div>

**Comment by livio-a** [comment]
Hi @astriffe

I converted the discussion to an issue, because there's actually a bug.
As the title of the issue already suggests, the userinfo claims (email, phone, ...) will be missing in the id_token, if you request an access_token as JWT with user roles inside it together with the userinfo inside the id_token.

I could reproduce it in production and locally and will deploy a fix as soon as possible (sometime today)

**Comment by astriffe** [comment]
Thanks a lot @livio-a for the lightning fast fix. 

Should this already have been rolled out, or do I see the status anywhere?

**Comment by fforootd** [comment]
Sorry that we not yet have a status which version is deployed 😀 

It is not yet deployed but I think we will rollout this soon. I keep you posted!

**Comment by livio-a** [comment]
@astriffe sorry initially wanted to deploy at noon, but didn't get around to it
but it is now on zitadel.ch

**Comment by astriffe** [comment]
Thanks for the responses, no need to be sorry :) I wasn't sure whether 'released' includes 'deployed' in your pipeline, but didn't want to put any pressure :) 

Thanks for fixing it so fast! 👍

**Comment by fforootd** [comment]
Yeah we separate release and deploy 😀 

It was also a good catch of you, so thank you for the report 👍
