### ISSUE TITLE
Backend Bugs

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#206]
Users:
- [x] SearchUsers state on inital users missing
- [x] If I register for global we should add org member ORG_PROJECT_CREATOR
- [x] Policy to check usernames for domains did not work on the org. caos 

Orgs:
- [x] Setup, No permission
- [x] Setup Org, User has own ID as ResourceOwner

Project:
- [x] Search Project Roles returns all roles not only from my project
- [x] Search Members returns wrong members
- [x] On Project Create we don't add member
- [x] Separate serachgrantedprojects
- [x] ProjectGrant View add ResourceOwner Name

General:
- [x] Failed Events, should add new row for each new sequence
- [x] Error of precondition validation should be more specific not only validation failed

Delete:
- [x] Delete Foreign Keys (if projectrole is removed we should remove it from all projectgrants and usergrants)

Management:
- [x] GeMyOrgIamPolicy

Login:
- [ ] [panic during password reset](https://github.com/caos/zitadel/issues/206#issuecomment-645257966) (could not reproduce only if we killed all pods)

UserGrant:
- [x] Its possible to add roles, that not exist

**Comment by adlerhurst** [comment]
I try to reset my password and get this error displayed after I set the new password and press enter: `upstream connect error or disconnect/reset before headers. reset reason: connection termination` 
My account is in the global domain.

**Comment by adlerhurst** [comment]
I still get the [this error](https://github.com/caos/zitadel/issues/206#issuecomment-645257966)

**Comment by adlerhurst** [comment]
Encoding of translations is wrong.
If i want to change my password in the profile section and send a wrong password as `current password` the enconding of the returned error message is wrong.
wrong password: 
![image](https://user-images.githubusercontent.com/27845747/85289770-3aa2d500-b498-11ea-88d5-24f8063a77ee.png)
error message:
![image](https://user-images.githubusercontent.com/27845747/85289855-5b6b2a80-b498-11ea-9141-acc3dab59bad.png)

**Comment by livio-a** [comment]
> Encoding of translations is wrong.
> If i want to change my password in the profile section and send a wrong password as `current password` the enconding of the returned error message is wrong.
> wrong password:
> ![image](https://user-images.githubusercontent.com/27845747/85289770-3aa2d500-b498-11ea-88d5-24f8063a77ee.png)
> error message:
> ![image](https://user-images.githubusercontent.com/27845747/85289855-5b6b2a80-b498-11ea-9141-acc3dab59bad.png)
> ![image](https://user-images.githubusercontent.com/27845747/85289950-7b9ae980-b498-11ea-8c91-9ba05838ead5.png)

@adlerhurst moved this to frontend bugs as the encoding is correct and must be handled by the client (e.g. insomnia does so)
