### ISSUE TITLE
Where is this BUILDARCH coming from?

### ISSUE THREAD

**Issue by gc-ss** [caos/zitadel#2064]
https://github.com/caos/zitadel/blob/26e4e607bc85b32f99e4295096436205462306c9/build/dockerfile#L21

**Comment by adlerhurst** [comment]
It's a predefined ARG variable of docker: https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope

**Comment by gc-ss** [comment]
@adlerhurst In that case, 2 questions:

1. shouldn't `BUILDARCH` be defined in the dockerfile: https://github.com/caos/zitadel/blob/26e4e607bc85b32f99e4295096436205462306c9/build/dockerfile#L21

2. Also, that specific line:

`FROM ${BUILDARCH}-base AS base` would resolve to something like `FROM x86_64-base AS base` or `FROM arm_64-base AS base` or something like that - yes?

Where would `x86_64-base` or `arm_64-base` images come from?

To give some context my docker builds are all failing with this dockerfile saying `BUILDARCH` isn't defined but before solving this specific problem, I would like to learn from you the 2 questions above.

**Comment by livio-a** [comment]
Hi @gc-ss 

`BUILDARCH` is a predefined ARG from docker itself. It requires the docker BuildKit backend. So the commands will only work if you prepend `DOCKER_BUILDKIT=1` before the actual docker command:
`COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1  && docker-compose -f ./build/local ...`
or
`DOCKER_BUILDKIT=1 docker build -f build/dockerfile . -t zitadel:gen-fe --target go-copy -o .`

The resolved docker steps `arm64-base` and amd64-base are defined just above:
https://github.com/caos/zitadel/blob/26e4e607bc85b32f99e4295096436205462306c9/build/dockerfile#L8-L9
https://github.com/caos/zitadel/blob/26e4e607bc85b32f99e4295096436205462306c9/build/dockerfile#L11-L12

We use this to automatically set ENV vars depending on the platform the docker build command is executed.
At the moment we only set the variable for downloading the specific protoc binary.

Regarding your docker build failures:
Did you run the docker / docker compose commands using `DOCKER_BUILDKIT=1`?
If so, can you provide me with some infos please:
 - Which version of docker do you have installed?
 - OS?
 - Arch? ARM / x68?

**Comment by gc-ss** [comment]
Appreciate this @livio-a 

The parent issue is https://github.com/caos/zitadel/issues/2063

> Did you run the docker / docker compose commands using DOCKER_BUILDKIT=1?

I did. The command I typed in is:

```
COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 \
&& docker-compose -f ./build/local/docker-compose-local.yml --profile database -p zitadel up --exit-code-from db-migrations \
&& sleep 5 \
&& docker-compose -f ./build/local/docker-compose-local.yml --profile database --profile init-backend --profile init-frontend --profile backend --profile frontend --profile setup -p zitadel up -d
```

> Which version of docker do you have installed?
latest

> OS?

Ubuntu 20.04

> Arch? ARM / x68?
x68

I am doing all of this on EC2

I can make any number of EC2 instances of any configuration available to you/your team - you just need to give me your public SSH key and I will enable access so you can duplicate what I can see

**Comment by gc-ss** [comment]
@livio-a  How does your `/etc/docker/daemon.json` look like?

**Comment by livio-a** [comment]
closing this with reference to https://github.com/caos/zitadel/issues/2063#issuecomment-887084055:
buildkit has to be enabled in deamon.json

fix for the linux local build with the docker compose file are we testing right now and will be discussed in #2063 and the corresponding PR (#2076)
