### ISSUE TITLE
(almost) blank screen after register new org

### ISSUE THREAD

**Issue by juergrinaldi** [caos/zitadel#2092]
After registering a new org (hitting the save button on the register form) I get an almost blank screen with only a almost empty header (only the logo and the documentation button). (see below)

it is solved by reloading but is a pretty bad UX as user might think it's broken. 

![image](https://user-images.githubusercontent.com/48990649/127437587-9bba4ae3-0177-4251-a266-1811ae20c92d.png)

Windows 10, Firefox 90.0.2

**Comment by livio-a** [comment]
there was a caching issue on our dev system... it's now fixed
