### ISSUE TITLE
Initializing e-mail lacks logo image

### ISSUE THREAD

**Issue by juergrinaldi** [caos/zitadel#2098]
ZITADEL Logo image is not shown in the initializing e-mail.

![image](https://user-images.githubusercontent.com/48990649/127457160-4b4883f7-d6c4-4aab-a5d5-a36c0bb4853b.png)

Image-Link leads to a 404 Error. This is the link:
https://ci6.googleusercontent.com/proxy/uJoUPgZw9b8G8xW9KwGnMAt4cEscRcCO8eP_iTmSrNOrSnBcBatnw45KwcTUvhArpK7O7Dv5FhdZQ6XbxRFtJWru0MfUqcWfv_tHE3oMzz59Qy_HDZrjj5lWCEM=s0-d-e1-ft#https://api.zitadel.ch/assets/v1/IAM/policy/label/logo-113024803727794211

Windows 10, Firefox 90.0.2, Gmail

**Comment by livio-a** [comment]
Google user content proxy does not like svg: https://stackoverflow.com/questions/51471607/email-thumbnail-url-changed-to-googleusercontent-com-in-gmail/51643787#51643787

**Comment by livio-a** [comment]
This has been solved a while ago by exchanging the SVG image with a PNG
