### ISSUE TITLE
[Console]: Passwordless Registration

### ISSUE THREAD

**Issue by livio-a** [caos/zitadel#2112]
As described in #2056 in Console:

Selfmanagement:
- [ ] the authenticated user will be able to use both AuthAPI calls (direct and message).
- [ ] When creating a link directly, a QR code will be displayed so the user can scan it with his desired device (e.g. phone) to open the registration page more conveniently.

Administration:
- [ ]  managers will be able to send registration link mails to their users

Custom texts:
- [x] Customize new mail text passwordless registrastion (IAM and Org)
- [x] Customize three new login texts passwordless promt, passwordless registration and passwordless registration done (IAM and Org)

**Comment by peintnermax** [comment]
@livio-a found another one: setPasswordlessText. so there are four right? :)

**Comment by livio-a** [comment]
> @livio-a found another one: setPasswordlessText. so there are four right? :)

yes in total there are 4 custom text starting with `passwordless` but setPasswordlessText is not new and should already be implemented
