### ISSUE TITLE
exponential backoff on signing key creation

### ISSUE THREAD

**Issue by adlerhurst** [caos/zitadel#2132]
I turned off some spooler handlers. One of them was the key handler in the auth-service. Which leaded to the problem that each instance of the backend created a key every 10 seconds. 

So my question is: Would it make sense and is it possible to increment the wait duration between creating keys instead of doing it every 10 seconds? 

I think @livio-a could have an opinion on that

**Comment by fforootd** [comment]
I would generally advise to use exponential backoff as pattern for failing task 😁

**Comment by livio-a** [comment]
sounds like a bug / missing check

the idea was to check for newer events (key creation) when no active key is in the projection table... so already some sort of backoff, though not exponential

@adlerhurst we should have a look at it together

**Comment by livio-a** [comment]
basically implementation was correct, but the query for new events checked with aggregate type `iam` instead of `keypair` 🤦 

@adlerhurst can you please verify / have a look at the PR
