### ISSUE TITLE
Token revocation

### ISSUE THREAD

**Issue by fforootd** [caos/zitadel#2163]
Some customers are interested in `token revocation`.

We should implement this according to https://datatracker.ietf.org/doc/html/rfc7009

**Comment by fforootd** [comment]
@livio-a out of curiosity have you seen the errata https://www.rfc-editor.org/errata_search.php?rfc=7009&rec_status=0

**Comment by livio-a** [comment]
No I did not notice that and at the moment it's just reported and not yet verified.

I generally agree that anyone getting an access_token could do much worse than revoking it. But should a resource server (for which the token is intended for) be allowed to revoke it as well?
I'm not sure yet. Although it could do so for public client anyway.

**Comment by fforootd** [comment]
I think we should allow api clients to revoke access tokens within the boundary of one project
