### ISSUE TITLE
Query Side Refactoring

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#2176]
- [x] #2931 

**fully implemented and merged to main**

- [x] IAM
  - [x] projection
  - [x] query (currently request on eventstore)
- [x] UserGrant
  - [x] projection (https://github.com/caos/zitadel/pull/2837)
  - [x] query (https://github.com/caos/zitadel/pull/2838)
- [x] Key
  - [x] projection (#2728)
  - [x] query (#2755)
- [x] AuthNKeys
  - [x] projection (#2801)
  - [x] query (#2820)
- [x] LinkedIDPs
  - [x] projection (https://github.com/caos/zitadel/pull/2583)
  - [x] query (https://github.com/caos/zitadel/pull/2751)
- [x] ExternalIDP
  - [x] projection (https://github.com/caos/zitadel/pull/2583)
  - [x] query (https://github.com/caos/zitadel/pull/2767)
- [x] PasswordComplexityPolicy (https://github.com/caos/zitadel/pull/2417)
- [x] PasswordAgePolicy (https://github.com/caos/zitadel/pull/2418)
- [x] LockoutPolicy (https://github.com/caos/zitadel/pull/2419)
- [x] PrivacyPolicy (https://github.com/caos/zitadel/pull/2431)
- [x] OrgIAMPolicy (https://github.com/caos/zitadel/pull/2432)
- [x] LabelPolicy
  - [x] projection (https://github.com/caos/zitadel/pull/2479)
  - [x] query (https://github.com/caos/zitadel/pull/2479)
- [x] LoginPolicy (https://github.com/caos/zitadel/pull/2401)
- [x] IDPConfig (https://github.com/caos/zitadel/pull/2411)
- [x] Org (https://github.com/caos/zitadel/pull/2342)
- [x] OrgDomain (https://github.com/caos/zitadel/pull/2383)
- [x] Features
  - [x] projection + query (https://github.com/caos/zitadel/pull/2578)
  - [x] fix und tests (https://github.com/caos/zitadel/pull/2610)
- [x] LoginNames
  - [x] projection (https://github.com/caos/zitadel/pull/2698 )
  - [x] view for other queries (https://github.com/caos/zitadel/pull/2698 )
- [x] Project (https://github.com/caos/zitadel/pull/2613, https://github.com/caos/zitadel/pull/2433)
- [x] ProjectGrant (https://github.com/caos/zitadel/pull/2433)
- [x] ProjectRole (https://github.com/caos/zitadel/pull/2433)
- [x] Application (https://github.com/caos/zitadel/pull/2576, https://github.com/caos/zitadel/pull/2612)
- [x] UserMembership
  - [x] query (member projections) (https://github.com/caos/zitadel/pull/2768)
- [x] OrgMember
  - [x] projection (https://github.com/caos/zitadel/pull/2699)
  - [x] query (https://github.com/caos/zitadel/pull/2796)
- [x] IAM Member
  - [x] projection (https://github.com/caos/zitadel/pull/2699)
  - [x] query (https://github.com/caos/zitadel/pull/2796)
- [x] ProjectMember 
  - [x] projection (https://github.com/caos/zitadel/pull/2699)
  - [x] query (https://github.com/caos/zitadel/pull/2796)
- [x] Permissions
  - [x] query (https://github.com/caos/zitadel/pull/2797)
- [x] ProjectGrantMember
  - [x] projection (https://github.com/caos/zitadel/pull/2699)
  - [x] query (https://github.com/caos/zitadel/pull/2796)
- [x] IDPProviders (needs mapping projection between `LoginPolicy` and `idp` which subscribes to `provider`-events)
  - [x] projection (https://github.com/caos/zitadel/pull/2590)
  - [x] query
- [x] MailTemplate
  - [x] projection (https://github.com/caos/zitadel/pull/2591)
  - [x] query (#2735)
- [x] MessageText
  - [x] projection (https://github.com/caos/zitadel/pull/2591 )
  - [x] query (#2735)
- [x] CustomText
  - [x] projection (https://github.com/caos/zitadel/pull/2591)
  - [x] query (#2735)

**Solve later (see https://github.com/caos/zitadel/issues/2176#issuecomment-974059476):**
- NotifyUsers
- Notifications
- UserSession
- Token 
- Styling

**Comment by livio-a** [comment]
keep https://github.com/caos/zitadel/issues/1117 in mind when migration UserGrants

**Comment by adlerhurst** [comment]
keep https://github.com/caos/zitadel/issues/2233 in mind when migrating user grants

**Comment by adlerhurst** [comment]
keep https://github.com/caos/zitadel/pull/2612#discussion_r750957068 in mind when migrating token

**Comment by livio-a** [comment]
as discussed with @adlerhurst I suggest to postpone the following into new separate packages:
 - Notifications (Notifications and NotifyUsers)
   - no heavy consumption
 - Authentication related stuff to the login refactoring (UserSessions, Token, internal query of users)
   - we have to ensure, that data requested by id especially with tokens, must be up to date
   - user sessions should be a better projection (computed states, ...)

**Comment by livio-a** [comment]
listMyProjectOrgs currently returns orgs either from orgs table or from user grants (depending on the management role)
the org details (e.g. creation date) is obviously missing in the user grants table. therefore is cannot be returned in the api

this should be easy to solve with the new projections

**Comment by adlerhurst** [comment]
list queries don't ensure the limits at the moment
