### ISSUE TITLE
Include assets into backups

### ISSUE THREAD

**Issue by stebenz** [caos/zitadel#2190]
From the discussion we had, we plan for the following parts to include assets into the backups:

- use cockroach native backup to backup to GCS and S3
- move logic to create backups of the database to zitadel-operator from the database-operator
- include assets, which are stored in S3, into state

**Comment by fgerschwiler** [comment]
In my opinion we can close this issue, because in ZITADEL V2 we will put all the assets to the cockroach db instead of s3 storage. What do you think? @livio-a @stebenz @eliobischof @adlerhurst
