### ISSUE TITLE
Back-Button in MFA / U2F / OTP missing

### ISSUE THREAD

**Issue by buehler** [caos/zitadel#2207]
**Describe the bug**
If a user clicks on either option to set up MFA or OTP, they have no option to go back. If browser-back is used, the "please reload this post form" occurs which then reloads the MFA / OTP site.

**Expected behavior**
There should be a back button if a user accidentally clicks on either option.

**Screenshots**
<img width="437" alt="back" src="https://user-images.githubusercontent.com/1067213/129533537-4d6f585c-d882-4a25-81e6-53b2ee045f83.png">

**Comment by livio-a** [comment]
Thanks @buehler for reporting.
This is actually a rendering bug. I've located the error and will deploy a fix within the next hours.

**Comment by livio-a** [comment]
fixed with #2224 and now deployed to production
