### ISSUE TITLE
"Enter" button (and back button) on OTP registration missing

### ISSUE THREAD

**Issue by buehler** [caos/zitadel#2208]
**Describe the bug**
If a user wants to register an authenticator app, there is no option to go back (related to https://github.com/caos/zitadel/issues/2207) and to actually proceed.

When the code from the authenticator is entered, some users need to press "enter" on the keyboard to proceed with the registration.

**Expected behavior**
There should be a "register" and a "back" button on this screen to show the primary actions.

**Screenshots**
<img width="399" alt="otp" src="https://user-images.githubusercontent.com/1067213/129534037-68d6a1e9-61a3-4cb7-aedc-f4ef7074acb9.png">

**Comment by livio-a** [comment]
Exactly the same underlying error as with #2207

**Comment by livio-a** [comment]
fixed with #2224 and now deployed to production
