### ISSUE TITLE
backend user metadata

### ISSUE THREAD

**Issue by peintnermax** [caos/zitadel#2228]
- [x] setting user metadata feature doesn't change,
- [ ] can't save metadata with symbols or umlauts just like {  or ö. - Unknown base64 encoding at char: {
- [ ] AuthService: Error on deleting some keys - Errors.Metadata.NotFound (META-ncnw3)
- [ ] MgmtService: Error on saving -  User could not be found (COMMAND-4M0fs)

**Comment by fgerschwiler** [comment]
I can't reproduce the second error. I encoded Hallöle with base 64 and it worked fine
