### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#2230]
**Quickstarts**
- Integrate ZITADEL Login in your App
   - Angular
   - React
   - etc.
- Secure your API
   - Go
   - .NET
   - etc. 
- Call the ZITADEL API
   - Go
   - .Net
   - etc...
- Librarys: List of all the librarys
- Identity Aware Proxy

**Guides**
- Get to know ZITADEL
  - Get started
  - Organizations
  - Projects
  - ... more resources to describe
- Technical Guides/Use Cases
  - Service Users
  - Access ZITADEL APIs
  - Identity Brokering
- Configure your Login
  - Identity Brokering
  - Login Policy
  - Customize Branding

**Manuals**
Describe each Setting by ZITADEL Menu, add links to useful guides or add use cases to resources
- Organization
  - Policies 
- Project
  - Roles
  - Application
  - Rol

**APIs**
- Domains
- Rate Limits
- Auth API
- Management API
- Assets API
- Admin API
- OpenID Connect & OAuth

**Concepts**
Fine as it is

**Legal**
Fine as it is

**Comment by fgerschwiler** [comment]
Some thoughts:
- Add Example Architecture for different Use Cases (Saas Product, --> Dev, Prod Project, Multiple Customers)

**Comment by livio-a** [comment]
regarding the apis, it might make sense to have some guides for them as well: describing the generell usage, differences / use cases

**Comment by fgerschwiler** [comment]
> regarding the apis, it might make sense to have some guides for them as well: describing the generell usage, differences / use cases

I think it will still be nice to generate the docs from the protos but maybe we will have to write our own generator. In my opinion stripe has really nice api docs: https://stripe.com/docs/api

**Comment by fgerschwiler** [comment]
closing this issue, because of multiple new ones for the different parts of the documentation
