### ISSUE TITLE
Login to Zitadel after logout in product using Zitadel

### ISSUE THREAD

**Issue by sueess** [caos/zitadel#2231]
**Describe the bug**
* If I logout in our application and I return to the Zitadel screen, I get a popup, which tells me to login again. That's great.
* If i click on the "einloggen" button nothing happens
* If I refresh the popup appears again
* If I clear the cache the pop appears again
* If i clean application data using the dev-tools in Chrome it works

**To Reproduce**
See description

**Expected behavior**
Best would be an automatic logout and a redirect on the login screen

**Screenshots**

**Desktop (please complete the following information):**
 - macOS BigSure
 - Chrome 92

**Comment by livio-a** [comment]
Hey @sueess 

Thanks for reporting this issue. We fixed this with #2267.
