### ISSUE TITLE
Improvement login flow

### ISSUE THREAD

**Issue by livio-a** [caos/zitadel#241]
- [x] Show LoginName / profile
- [ ] Back Buttons

**Comment by juergrinaldi** [comment]
loginview with loginname/displayname/usericon.
not that title and text are new centered to provide a pleasant arrangement of the UI elements. (in case it collides with other views, please report back)
![image](https://user-images.githubusercontent.com/48990649/87538161-105dc500-c69c-11ea-8e08-1e0514c7d054.png)

Here the version without a displayname where the loginname is in its place instead. and also without a individual usericon (if that case is possible)
![image](https://user-images.githubusercontent.com/48990649/87538219-28354900-c69c-11ea-9da0-4f9379dd4c3d.png)

**Comment by livio-a** [comment]
see changes in https://github.com/caos/zitadel/pull/485#issue-450958940
