### ISSUE TITLE
Enable create verified domains

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#2415]
We should be able to set on a org, if domain verification is needed. (OrgIAMPolicy)
This is can be needed if you have a dedicated instance and you manage all the customers.

**Comment by fgerschwiler** [comment]
@livio-a Am I right that for ZITADEL v2 we should have this as default, if some tenants will need the verification they should be able to enable it?

**Comment by livio-a** [comment]
IMO not necessarily as default, but we have to enable this per instance
