### ISSUE TITLE
UX: Move button to add additional roles to bottom of the list

### ISSUE THREAD

**Issue by mffap** [caos/zitadel#2451]
**Describe the bug**
If you add multiple roles the button to add additional stays on top. To add a new role, you have to scroll up.

**To Reproduce**
add multiple roles until button on top is out of view

**Expected behavior**
add new roles without scrolling to top

**Screenshots**
![image](https://user-images.githubusercontent.com/1366906/135594746-3dc806a7-77a6-4397-91cc-21221da6b8d8.png)

**Comment by juergrinaldi** [comment]
The usual way is to put the 'New Role' Button on the end of the Input List. (I'd place it where the delete button is and put the delete button on the same line but right aligned)

Another option could be to inverse the input list, meaning that new roles appear on top. that way you wouldn't have to scroll for new items. it's a bit more unorthodox but could still work, depending on how important the descending list order is.
