### ISSUE TITLE
Saving password complexity fails

### ISSUE THREAD

**Issue by eliobischof** [caos/zitadel#2492]
Environment: dev
Project: caos-demo

Errors.Org.PasswordComplexityPolicy.NotFound (ORG-Dgs3g)

![image](https://user-images.githubusercontent.com/12727842/136574357-0963bc45-9a24-4f10-aaf7-3cc3d791978b.png)

**Comment by fgerschwiler** [comment]
I just tried this and it looks like it is solved, due to this I will close this issue. If it reappears we will reopen the issue
