### ISSUE TITLE
Correct workaround in ZITADEL Dockerfile for bugs in version "latest" of CockroachDB-binary

### ISSUE THREAD

**Issue by stebenz** [caos/zitadel#2523]
For the CockroachDB unit-test normally the latest version of the binary is downloaded, but in this instance there is a change which generates problems with migration 1.26.

```
#37 202.0 time="2021-10-14T09:49:48Z" level=fatal msg="migrations failed" error="exec file: /go/src/github.com/caos/zitadel/migrations/cockroach/V1.26__current_sequence_table.sql || err: pq: constraint \"primary\" of relation \"current_sequences\" does not exist" logID=REPOS-jehDD
```

To have a workaround, we set the version of the used CockroachDB-binary to 21.1.7 and included it into the Dockerfile, additionally we set the env-variable "COCKROACH_BINARY" which sets to use the downloaded binary.

```
ARG COCKROACH_BINARY=cockroach
RUN apt install openssl tzdata tar

RUN mkdir /usr/local/lib/cockroach
RUN wget -qO- https://binaries.cockroachdb.com/cockroach-v21.1.7.linux-amd64.tgz \
    | tar  xvz && cp -i cockroach-v21.1.7.linux-amd64/cockroach /usr/local/bin/
RUN rm -r cockroach-v21.1.7.linux-amd64
```

As we can't change the already existing migrations we have to either wait for a fix of the problem on CockroachDB-side or find a way to update the binary so that the migrations still work.

Could be from a change like https://github.com/cockroachdb/cockroach/releases/tag/v21.1.9

**Comment by fgerschwiler** [comment]
After clarification with silvan this issue can be closed.
