### ISSUE TITLE
[Frontend] Grant List shows that no grants were found, if the request to load the list times out.

### ISSUE THREAD

**Issue by maennchen** [caos/zitadel#2663]
**Describe the bug**

**To Reproduce**
1. Go to a granted Project that has one or more grants
2. Wait for request to time out (Possible because of https://status.zitadel.ch/incidents/64971)
3. The list shows the message `No authorization found`

**Expected behavior**

An error is shown. The list is not empty but it could not be loaded.

**Screenshots**
Not added since it shows customer information.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10 on Linux 5.13.0-21-generic
 - Browser: Google Chrome
 - Version: 95.0.4638.69

**Smartphone (please complete the following information):**

n/a

**Additional context**

* It takes a very long time for that request to time out. I did not measure it, but it was for sore more than 5 minutes.

**Comment by adlerhurst** [comment]
Hi @maennchen thank you for your report.

We will have a look at it and try to clarify if the list is empty because of an error or not and the timeouts.

**Comment by fgerschwiler** [comment]
@peintnermax The text "no authorization found" is always shown if no data is existing, no matter if an error occured. Also the error is not handled, we should at least show the error.
