### ISSUE TITLE
Check roles on Authentication not working

### ISSUE THREAD

**Issue by maennchen** [caos/zitadel#2664]
**Describe the bug**

All of our Projects have the `Check roles on Authentication` checkbox enabled. User without any roles are however still able to log in.

**To Reproduce**
1. Setup Project / Client
2. Enable `Check roles on Authentication`
3. Add User Authorization, but do not add any roles
4. Log In

**Expected behavior**
The user should not be able to log in.

**Screenshots**

n/a

**Desktop (please complete the following information):**

n/a

**Smartphone (please complete the following information):**

n/a

**Additional context**

We did grant other organizations for the projects in question. There's also no roles assigned to the user in any granted project.

**Comment by adlerhurst** [comment]
Hi @maennchen 

Thank you for your report. We think there is a mismatch between the description and the implementation of the check. Currently as soon as an authorization exists the user is allowed to log in, regardless if any the user is granted any role.

We will check and give you a feedback by the beginning of next week.

**Comment by livio-a** [comment]
Hey @maennchen 

We have discussed it internally and are still unsure how to proceed.
As we're trying to figure out the real use cases, we see three possibilities during authentication:

1. users without authorization
2. users with authorization, but no role
3. users with authorization and role(s)

In the future, there might even be a forth option to check for users with certain role(s) in an authorization.

From your description we believe you need to differ between 2 and 3.
Is that correct? And If so, could you please explain us why?

**Comment by maennchen** [comment]
@livio-a I have actually never thought about it. I just assumed that it is enough to remove the roles from the authorization is enough because of the checkbox label.

I think it is a fine solution for me to reword the label to something along the lines of `Check authorization entry on Authentication` and keep the functionality as-is.

Since this is the issue, I will try to remove the authorization itself and then test if it behaves as expected with your given information.

**Comment by fgerschwiler** [comment]
- [ ] Rename Check roles on authentication to something like "Check authorization entry on Authentication"
