### ISSUE TITLE
[Service Users]: PAT

### ISSUE THREAD

**Issue by livio-a** [caos/zitadel#2702]
Some clients have problems integrating service accounts with JWT Profile (signing / 3rd party integration does not support, ...)

Although less secure than JWT Profile, we should offer the possibility to create some sort of PAT (long living token).

First suggestion is to enable PAT along with JWT Profile keys. So it's up to the users to decide which option they want to use.
The token will grant access to all rights assigned to the user (within ZITADEL itself (manager roles) or in other projects by user grants).

Notes for Implementation:
- Might need some changes on the Userinfo / Introspection Endpoints: audience check, granted scopes, ...
- We might have to prefix tokens / have a semantic for them to easier query the database.

**Comment by livio-a** [comment]
#2974 now implements the following:

Upon creation only the scope `openid` is granted.

Changes to / impact on OIDC / token mechanism:
- All ZITADEL APIs will now skip audience check if the received token is a PAT.
- Userinfo will return sub (only `openid` scope is really granted)
- Introspection will skip audience check for PAT as well, implicitly add all role scopes of the requesting project and return active (if not expired), scopes, sub and all role claims (assigned to the user in that project)
- Revocation will not be possible as the token is not issued to a specific client

The question still is if Users must be able to change this behaviour above, for example:
- allowing the token to be used for ZITADEL or not (might be done by scope as well)
- grant more scopes
  - audience scopes
  - metadata
  -resourceowner
  - specific roles
- ...

Since users can create multiple tokens anyway, this would not be a problem for us but would rather give them even more options.
To reduce the complexity for inexperienced users, we could either enable the options above by checkboxes or predefined scopes in Console.

@fforootd any input?

**Comment by fforootd** [comment]
> allowing the token to be used for ZITADEL or not (might be done by scope as well)
> grant more scopes

👍 I think we should allow the user to add additional scopes to the PAT. This makes the UX somewhat like other providers.

Btw. I think we should also allow `humane` users to create `PATs` and not only `machines`

**Comment by livio-a** [comment]
> > allowing the token to be used for ZITADEL or not (might be done by scope as well)
> > grant more scopes
> 
> 👍 I think we should allow the user to add additional scopes to the PAT. This makes the UX somewhat like other providers.
> 
> Btw. I think we should also allow `humane` users to create `PATs` and not only `machines`

but would you let the users select the scopes from predefined options (checkboxes, like others do), or would you let them set them freely (textbox)? or did you mean to combine both possibilities?

**Comment by livio-a** [comment]
as discussed this week: we will start with PAT for service user only

only change / addition to the [comment above](https://github.com/caos/zitadel/issues/2702#issuecomment-1009664337) is that users cannot request scopes themself and not only scope `openid` is granted by default, but `urn:zitadel:iam:user:metadata` and `urn:zitadel:iam:user:resourceowner` as well

**Comment by ilyashtrikul** [comment]
Hi, please, could you get back to the question about (human) user's PAT. For example, this feature is very useful when you need authenticate console applications (like docker, terraform etc.) and you need exactly human account. I know, there is special oAuth flow for this case with special redirect to application, but with PAT it's more simply.

**Comment by livio-a** [comment]
Hey @ilyashtrikul 

Sorry for the late feedback. We are very busy right now with the preparations for version 2.

By the specific OAuth flow, did you mean the [Device Code Flow](https://datatracker.ietf.org/doc/html/rfc8628)? IMO that would be the best solution.  The token would be issued for an OAuth client to a user, who authenticated using the "normal" mechanics. He could reuse existing sessions and 2FA/MFA checks would apply if needed.

It's also possible to use the "normal" Authorization Code Flow with a temporary server listening for the callback. We've used this before for a cli and if I checked the docs of Terraform correctly, they do so as well: https://www.terraform.io/internals/login-protocol
Again this would allow to reuse existing sessions and still not weaken the security.

There's also theoretically the Resource Owner Password Credentials flow (Terraform allows it in certain situations), which is fortunately removed with OAuth 2.1. And we will not offer it in ZITADEL for security reasons either.

Nevertheless I see the point in adding PATs for human users as well. As with service accounts, not all tools support the provided auth mechanisms. But we then need to allow users to request scopes / restrict access for PATs. For service accounts you can easily create a separate account (specifically for that use case) and grant this account only the required project(s) or manager role(s). With an existing user (possibly an ORG_OWNER or even IAM_OWNER) you don't want to create a PAT which will inherit all the user's permissions.

@fforootd any input or can we discuss this after your holidays?
