### ISSUE TITLE
Zitadel Console UI/UX

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#275]
General:
- [ ] Use same style of buttons every where
- [x] Farbschema abstimmen (Login und Zitadel) (@juergrinaldi bringt farbschema)
- [x] Schriftarten vereinheitlichen
- [ ] Have a look on smaller screens
- [ ] Description texts less prominent
- [ ] Styling general, material? input fields
- [ ] states in color
- [ ] remove box collapses everywhere
- [ ] Filters on all lists
- [x] On lists pagination problems
- [ ] show state on each side at the same place (@juergrinaldi )
- [x] On delete actions show prompt: are you sure...

Main Page:
- [x] Remove first sentence
- [ ] Should show introduction if user is first login
- [ ] User Search Component, if user found route to user detail, else to create user
- [ ] Some Functionalities based on my role (For each menu point, with some description)

Menu Bar
- [x] Instead of pink point (Iam User), Show line under the menu bar with text attention you are a iam admin, you can manipulate everything
- [x] Avatar should be the same everywhere
- [x] show preferred login name of user instead of username
- [ ] organisations show last used, else search orgs if there are to many
- [x] rename to logout all users, at the moment it doesnt work
- [x] Add Organisation remove domain verification part
- [x] Add Organization step 2 remove address formular
- [x] Add Organisation step 2, password should not be required
- [x] Show preferred loginname of the user, if its only username its possible to have duplicates

Menu
- [x] structure menu in parts devider
- [x] IAM should be the last point rename to administration
- [x] remove logout button
- [x] Projects should have submenu, projects granted projects
- [ ] Add menu point authorizations

Organisations
- [ ] Add Search functionality
- [ ] List instead of tiles
- [x] Text: Select your organisation

Personal Information
- [x] Side Nav with changes
- [x] Theme switcher smaller (@juergrinaldi makes design)
- [x] Loginnames at the top
- [x] Password remove inputfields, call to action
- [x] Password text, depending on policy
- [x] Remove Address part (because we don't have structured data at the moment)
- [x] Email and Phone Label not uppercase
- [x] Description Texts (@fforootd )
- [x] OTP: Show states with icon

Organisation
- [x]  state not translated
- [x] in side nav only primary domain
- [x] new domain not as input field, call to action (add domain)
- [x] primary as star
- [x] show only modify button
- [x] on policy detail show if its default, if not reset to default button

Projects
- [x] If no granted projects dont show it
- [x] projects and granted projects not on same site, because of submenu
- [x] if less than 5 projects show tiles else tables
- [x] Granted projects show resourceowner name
- [x] on tiles remove 3 points in the right bottom, remove activate, deactivate
- [x] remove selctors
- [x] project detail, button to deativate on title line rigth side
- [x] rename grant to granted organisations
- [x] granted organisations remove domain column
- [x] granted organisations dont show members and roles, --> go to detail
- [ ] make nice desing for roles by group (@juergrinaldi )
- [x] sidenav remove type
- [x] Project tiles last modified and created in english even if i have german

Granted Projects
- [x] On Granted project list should not be the name of the granted org, it should be the resource owner, so I know who gave it to my org

Applications:
- [x] Create process (@livio-a @juergrinaldi) #466

Users
- [x] dont show multifactor if no existing
- [x] Activate deactivate button on title line right side
- [x] remove address part
- [x] rename grants to authorizations

Managers
- [x] Generate color for users
- [x] Don't show icon, show user initialen

Activity
- [x] If last changes dont load more

**Comment by juergrinaldi** [comment]
Status for items
![image](https://user-images.githubusercontent.com/48990649/86229887-a3710800-bb90-11ea-905e-f4bc29214cc1.png)
![image](https://user-images.githubusercontent.com/48990649/86229922-b08df700-bb90-11ea-95f9-1ca7bb623155.png)

**Comment by juergrinaldi** [comment]
Theme switch:
![image](https://user-images.githubusercontent.com/48990649/86230009-ce5b5c00-bb90-11ea-99c6-b3dcce9d2640.png)
I'd also implement the switch on a global scale either in the menubar on the bottom or in the user-dropdown (top right).
(and remove it completely in the 'personal information' section. (as it isn't a personal information really)

**Comment by juergrinaldi** [comment]
some inputs/changes regarding design and usability:
(most of it to consolidate login and app)


**Design adjustments Login/In-App:**
[ ] No Capslock (except Labels)
[ ] Font: Lato (completely, except Logo)
[ ] Fontweight H1: light (300)
[ ] Primarycolor: #3574C6
[ ] Border-color Cards: #505050
[ ] swap Flavorimage (see Screenshot/Attachement)
[ ] darkdesign: default font: #BBBBC8, light (300)
[ ] in-App: Buttons as on Login (Primary/Secondary)
[ ] unifying all Elements (unified Dropdowns, Inputs, Buttons, etc...)


**Usability:**
[ ] Hovereffects for all Clickables (for example: see Material Design)
[ ]Placeholder text too dominant
[ ] set margin/padding bottom on the content page to at 70px
[ ] replace bottom-line Input fields (material design) with full border Inputfields.

**Comment by juergrinaldi** [comment]
**New Login Page Design** (consolidated with the app):
![image](https://user-images.githubusercontent.com/48990649/86354595-996f0800-bc69-11ea-826d-0c67019c3db6.png)

![image](https://user-images.githubusercontent.com/48990649/86354619-a8ee5100-bc69-11ea-99d2-9d134a439c4c.png)

here are some views simulating different screen-/browser sizes:
![image](https://user-images.githubusercontent.com/48990649/86354676-bd324e00-bc69-11ea-8824-e27b1629a4d7.png)

**Comment by juergrinaldi** [comment]
Here's my first attempt at role groups. please review it for functionality, as I wasn't sure about how it's supposed to work. ^^
![image](https://user-images.githubusercontent.com/48990649/87040610-4230e080-c1f1-11ea-8ae3-076694b73dc5.png)
