### ISSUE TITLE
Invalid aud claims

### ISSUE THREAD

**Issue by astriffe** [caos/zitadel#2774]
**Describe the bug**
The aud claim of our id tokens do no longer contain the client ids of our applications in the project and therefore, the UI can no longer authenticate to the backend service (as it validates the aud claim).

**To Reproduce**
1. Get a token
2. read the aud claims
3. compare with the client ids of the apps in the respective project

**Expected behavior**
The aud claim contains our client ids

**Comment by fgerschwiler** [comment]
hi @astriffe 
Thanks for your report.
We just published the error on our status page: https://status.zitadel.ch/

**Comment by fgerschwiler** [comment]
Hi @astriffe 

We just deployed our fix. Can you test it again and give us some feedback?

**Comment by astriffe** [comment]
Thanks @fgerschwiler, seems to be working as expected again 👍
