### ISSUE TITLE
logout with expired token fails

### ISSUE THREAD

**Issue by adlerhurst** [caos/zitadel#279]
If i logout in console with an expired token i get an error `id_token_hint invalid` as response from accounts.

![image](https://user-images.githubusercontent.com/27845747/85714646-eb081780-b6ea-11ea-8472-7539ce7887fa.png)

**Comment by livio-a** [comment]
could only find the following in the session management specs:

- RP-Initiated Logout (https://openid.net/specs/openid-connect-session-1_0.html#RPLogout)
> id_token_hint
> RECOMMENDED. Previously issued ID Token passed to the logout endpoint as a hint about the End-User's current authenticated session with the Client. This is used as an indication of the identity of the End-User that the RP is requesting be logged out by the OP. **The OP need not be listed as an audience of the ID Token when it is used as an id_token_hint value.**

- Security Considerations (https://openid.net/specs/openid-connect-session-1_0.html#Security)
> The id_token_hint parameter to a logout request can be used to determine which RP initiated the logout request. Logout requests **without a valid id_token_hint** value are a potential means of denial of service; therefore, OPs may want to require explicit user confirmation before acting upon them.

@fforootd do you know if you should be able to log out with an expired id_token?

**Comment by fforootd** [comment]
I think we should accept the expired id_token.

We still need to validate the users state with the cookie placed in the user-agent.
So it might be a security benefit to check that this id_token (even when expired) was issued to that specific user-agent.
This could IMO be done by storing a hash or id inside the token to bind the cookie to the token.

@livio-a what do you think of this?
