### ISSUE TITLE
User in wrong organization after Self Register

### ISSUE THREAD

**Issue by MajaEffenberg** [caos/zitadel#2822]
**Describe the bug**
When a new user Self Register himself from the login window in our application, the user is created in the wrong organization.
He should be created in our organization that owns this project, however it is created in the "Global" organization.

**Expected behavior**
When user Self Register himself in the application login window, he is created in the organization that owns the project.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/89073193/145398402-4a6f4917-a2a3-4f0b-9567-769f62397b8a.PNG)

**Comment by livio-a** [comment]
Hey @MajaEffenberg

To let a user register on a specific organisation, you'll have to specify it via the primary domain scope: `urn:zitadel:iam:org:domain:primary:{domainname}`
If not specified we will always register the user in the `Global` organisation.

**Comment by mffap** [comment]
@livio-a @peintnermax could we make this more visible in the console? We could provide a visible hint on how to trigger org/project specific features.

**Comment by MajaEffenberg** [comment]
@livio-a Thank you for your quick reply, the appropriate primary domain specify in scope solved our problem.

@mffap It would be great to have hint in the documentation or console about these settings.

**Comment by livio-a** [comment]
in terms of hints in Console this relates to https://github.com/caos/zitadel/issues/1677

and I'll add it in the docs this week

**Comment by fgerschwiler** [comment]
closing this issue, because it is resolved
