### ISSUE TITLE
Can't deploy to Kubernetes 1.22: no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1

### ISSUE THREAD

**Issue by karfrank** [caos/zitadel#2826]
**Describe the bug**

I'm getting the following error when I try to deploy to a v1.22 Kubernetes cluster: 

```
zitadelctl takeoff
ts="2021-12-10T17:46:15Z" err="failed to deploy zitadel-operator into k8s-cluster: no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"" src="mypath/zitadel/cmd/zitadelctl/cmds/root.go:38"
```

This is because `CustomResourceDefinition` *apiextensions.k8s.io/v1beta1* was [removed from the API](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes)

I fixed the error by updating the version to `v1` in `pkg/kubernetes/artifacts.go`, for example [here](https://github.com/caos/zitadel/blob/main/pkg/kubernetes/artifacts.go#L94).

Afterwards I got the following error:

```
zitadelctl takeoff
ts="2021-12-10T18:00:13Z" err="failed to deploy zitadel-operator into k8s-cluster: applying crd zitadels.caos.ch failed: CustomResourceDefinition.apiextensions.k8s.io "zitadels.caos.ch" is invalid: [spec.scope: Required value, spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required]" src="mypath/zitadel/cmd/zitadelctl/cmds/root.go:38"      
```

This is because the YAML definitions ([here](https://github.com/caos/zitadel/blob/main/pkg/kubernetes/artifacts.go#L451-L568) and [here](https://github.com/caos/zitadel/blob/main/pkg/kubernetes/artifacts.go#L95-L219)) need to be updated to the [new spec](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#specify-multiple-versions) 

Afterwards I was able to deploy the operator. 

**To Reproduce**
See above

**Expected behavior**
I can deploy to a 1.22 Kubernetes cluster

Would you like me to raise a PR with my updates?

**Comment by fforootd** [comment]
@stebenz @eliobischof

**Comment by stebenz** [comment]
@karfrank I newly generated the CRD-definitions for Kubernetes v1.22, with this there shouldn't be any problems.
I took the freedom myself to create a PR with the changes, so you don't have to.

**Comment by eliobischof** [comment]
@karfrank sorry for the delay.

Could you please try it again using zitadelctl version 1.69.5?
