### ISSUE TITLE
Refreshed access token does not contain roles

### ISSUE THREAD

**Issue by astriffe** [caos/zitadel#2865]
**Describe the bug**
If I request a new token using a given refresh token (using angular-oidc), the new token does no longer contain the users roles.

**To Reproduce**
1. Login, retrieve access token. Right now, it contains the claim "urn:zitadel:iam:org:project:roles", as configured in the console.
2. invoke the library method `refreshToken()` - Refreshes the token using a refresh_token. 
3. Inspect the new access_token. Above mentioned claim is no longer present on the token

**Expected behavior**
Having all configured claims both on the original token and on the 'refreshed' tokens

**Comment by livio-a** [comment]
Hey @astriffe 

I tested (not using the mentioned library) and the refreshed access_token (JWT and Userinfo with Bearer) sill contained the claim.

@peintnermax could you please check if the angular lib does not map custom claims when refreshing.

**Comment by astriffe** [comment]
Thanks a lot @livio-a. 
I inspected the token directly in the chrome dev console -- even before the library made its job. And decoding these two token answers using jwt.io, I can't see any roles claim on the second token I receive. I'll be very happy sharing the token info with you, but I guess github isn't the right place for this ;)

**Comment by livio-a** [comment]
Hey @astriffe 

We found a bug on our side. When refreshing the token you can either send a scope for the new access_token or omit it. If omitted the origin scope (including the one for the roles) will be used. If you send a scope, which the library does, we accidentally don't assert the role scope again.
I'll try to implement a fix today.

**Comment by livio-a** [comment]
Hey @astriffe 

We deployed a fix and successfully verified it on production. Let us know if everything works out for you as well (or not).

**Comment by astriffe** [comment]
Thanks @livio-a , I can confirm that everything looks good now 👍 Thanks!
