### ISSUE TITLE
Initialization mail sent for verified users (console)

### ISSUE THREAD

**Issue by mffap** [caos/zitadel#2909]
**Describe the bug**
`Email verified` is checked, and email is sent to the user

**To Reproduce**
1. Users > New
2. Enter Details
3. Check "Email verified"
4. Create
5. Check inbox

**Expected behavior**
As indicated in the info box: no email

**Screenshots**

![image](https://user-images.githubusercontent.com/1366906/147769814-c412f208-087b-4ad3-a766-9835265cb091.png)

![image](https://user-images.githubusercontent.com/1366906/147769711-168af0b1-17d6-4af5-8aa8-da9f72749c13.png)

**Comment by fgerschwiler** [comment]
@mffap this is correct, because the user has to set a password
we already work on a solution, that an administrator is able to set an initial password 
@peintnermax can you tell more about the timeline of the fix?

**Comment by mffap** [comment]
But then the text in the infobox is not correct. This should be consistent with the behavior of the application.

**Comment by fgerschwiler** [comment]
yes thats correct. the text is wrong

**Comment by peintnermax** [comment]
Does this fix the problem for now? #2920

**Comment by mffap** [comment]
It solves only the wording. 
I'm still not clear on the process, though. Why does the user has to "finish initialization"? Whats the benefit of that step then? Is this explained in the manual?

**Comment by fgerschwiler** [comment]
We also need a code if the user needs to set a password, so no one else can set a password for this user.
But de message is still wrong, because on init user the mail is for two things, email verification and password setting.
So we need a possibility to set an initial password and the message should be something like if the email is already verified and a password is set, the user will not receive an email.

**Comment by peintnermax** [comment]
I've added the capability to set a password. Would this wording be correct? 
<img width="651" alt="Bildschirmfoto 2022-01-03 um 16 16 46" src="https://user-images.githubusercontent.com/10165752/147947480-27de65a6-e38a-45ee-80b1-4ce8590e522d.png">

**Comment by peintnermax** [comment]
this is the PR #2920

**Comment by fgerschwiler** [comment]
no it is still the same wording for me, this message says that if I check the checkbox for email verified, that I get no email. but this is only correct in combination with the initial password. or does the message change, when i haven't checked the box for "set initial password"?
