### ISSUE TITLE
always add orgId to memberships

### ISSUE THREAD

**Issue by peintnermax** [caos/zitadel#2927]
Always add orgId to the membership response such that the user can navigate to the location to manage his roles. Currently only memberships of org members contain the orgId.

**Comment by fgerschwiler** [comment]
dont you have this on the object details on the resource owner?

**Comment by peintnermax** [comment]
this is for the auth user detail where we will have a table of the users memberships. The request is listMyMemberships.

<img width="765" alt="Bildschirmfoto 2022-01-05 um 15 47 20" src="https://user-images.githubusercontent.com/10165752/148237055-01215f0a-6b77-4c58-a492-c63a6645fb41.png">
s

**Comment by fgerschwiler** [comment]
@peintnermax which organisation do you need? the org Id where the memebership belongs or the orgid of the resourceowner of the user

**Comment by peintnermax** [comment]
where the membership belongs.. i need it to set the org id as context

**Comment by fgerschwiler** [comment]
@peintnermax I just had a look at this. You get the objectdetails on each membership, in there you have the resource_owner. I think this is exactly what you need
