### ISSUE TITLE
ZITADEL implementations to enable virtual instance

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#2988]
To enable customers to get a virtual ZITADEL instance for them self, we need some changes in the ZITADEL backend.

- [x] #3056
- [x] #3214 
- [x] #3057 
- [ ] #3058 
- [ ] #3059
- [x] #3060
- [x] #3063 
- [ ] #3181
- [ ] #3223 
- [ ] #3224 
- [ ] #3225 
- [ ] #3222 
- [x] #3146

**Comment by fforootd** [comment]
@fgerschwiler We also need to serve `grpc-web` from the application.

**Comment by fforootd** [comment]
## Licensing

IMO the feature to run multiple virtual ZITADEL instances should be considered only for the commercial version.
The OSS version should be restricted to run one virtual only.

**Comment by fforootd** [comment]
@fgerschwiler I added #3181 to this issue
