### ISSUE TITLE
system handler should react to domain changed event

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#3062]
The system handler part of the zitadel should be able to handle an domain changed event, which will be sent to the cdn integration and call some api (e.g fastly, etc.). 

**Acceptance criteria**
- [ ] Handle domain.changed event
- [ ] Send to cdn

**Comment by fgerschwiler** [comment]
Define which api should be integrated

**Comment by fforootd** [comment]
Right now we are testing cloudflare, fastly and akamai.

To make an example with fastly the following steps apply:

- add domain name to service https://developer.fastly.com/reference/api/services/domain/
- create tls subscription https://developer.fastly.com/reference/api/tls/subs/
- prompt the user to create a cname pointing towards our infrastructure
- poll the certificate status and present the status to the user

**Comment by fgerschwiler** [comment]
this should happen in the customer portal, due to this , this issue will be closed
