### ISSUE TITLE
Refactor Pipeline

### ISSUE THREAD

**Issue by fforootd** [caos/zitadel#31]
Relates to https://github.com/caos/zitadel/pull/30

- [ ] Create debug-image
- [ ] Abstract Short-SHA
- [ ] Test NPM Build
- [ ] Configure SEMREL to upload release artifacts
- [ ] Maybe Generate Pre-Release Uploads from feature branches

**Comment by adlerhurst** [comment]
@fforootd is it still open? IMO the new dockerfile does most of the bulletpoints

**Comment by fforootd** [comment]
thats true

we can close this for the moment
