### ISSUE TITLE
CRD deployment style does not correctly unmarshal YAML

### ISSUE THREAD

**Issue by Brand2** [caos/zitadel#3107]
**Describe the bug**
The API definitions for deploying Zitadel on Kubernetes using the [CRD style](https://docs.zitadel.ch/docs/guides/installation/crd) result in incorrect objects being created within the cluster, which results in a nil-pointer dereference (in the case of the database operator) or continual printing of error messages (in the case of the Zitadel operator).

**To Reproduce**
1. Have access to a Kubernetes cluster - I have tested this on a local cluster deployed with `kind` on Ubuntu
2. Deploy the CRDs and operators using `zitadelctl takeoff`
3. Modify [`database.yml`](https://docs.zitadel.ch/assets/files/database-51ebbd568effd89805227c7afc1be4a9.yml) and [`zitadel.yml`](https://docs.zitadel.ch/assets/files/zitadel-9d6f8ed2288d244a079057a4339f02a0.yml) as appropriate for the cluster environment
4. Apply either database.yml, zitadel.yml, or both
5. View the created cluster objects by running `kubectl get Database -n caos-system -o yaml` and `kubectl get Zitadel -n caos-system -o yaml` and note the the `database` and `iam` keys respectively are now empty objects
6. Note that the database operator pod is now likely in a crashloop, and the Zitadel operator is likely printing a continual string of `unknown iam kind` errors.

**Expected behavior**
The objects generated within the cluster should match those submitted.

**Additional context**
I took some time to track down where I thought this might be occurring, as it was puzzling me when I encountered it. I took a look at the desired state in the [Zitadel operator](https://github.com/caos/zitadel/blob/main/operator/zitadel/kinds/iam/zitadel/desired.go) and the [database operator](https://github.com/caos/zitadel/blob/main/operator/database/kinds/databases/managed/desired.go) and these looked sane to me.

This lead me to think that maybe it was some weird behaviour with the CRDs and how the API extensions were working, so I took a look in the API spec for both the zitadel-operator and the database-operator, and noted that both have an empty struct (as a pointer to the `Empty` type) for the fields which I was noting would become empty objects (see [here](https://github.com/caos/zitadel/blob/main/operator/api/zitadel/v1/zitadel.go#L43) for the zitadel-operator and [here](https://github.com/caos/zitadel/blob/main/operator/api/database/v1/database.go#L43) for the database-operator). Please correct me if I am wrong, but I believe that these should likely be the [Spec type](https://github.com/caos/zitadel/blob/main/operator/zitadel/kinds/iam/zitadel/desired.go#L20) from the `github.com/caos/zitadel/operator/zitadel/kinds/iam/zitadel` package and the [Spec type](https://github.com/caos/zitadel/blob/main/operator/database/kinds/databases/managed/desired.go#L18) from the `github.com/caos/
zitadel/operator/database/kinds/databases/managed` package respectively - Though this assumes that the `Database` kind works only for managed versions, not provided databases. Another option would potentially be to declare them as `map[string]interface{}` types, but that doesn't seem ideal.

I may get a chance to make the changes in a local copy, build it, and test it on a local cluster within a week or two, but not likely this week, so wanted to make this issue to document it in case I have encountered an error which was not my own doing. I would like to add finally that the [GitOps method](https://docs.zitadel.ch/docs/guides/installation/gitops) works without issue.

**Comment by fforootd** [comment]
@eliobischof you might want to look into this

**Comment by Brand2** [comment]
One thing I forgot to mention last night when I made this issue (sorry, it was quite late) was that the `kubectl.kubernetes.io/last-applied-configuration` annotation for the objects matched exactly the YAML which I had submitted through `kubectl`.

**Comment by eliobischof** [comment]
I'll try to reproduce it as soon as I've fixed #3095, which relates to #3066.

**Comment by skuethe** [comment]
Exact same issue here trying to "install on CRD mode"

```bash
$ zitadelctl -v
zitadelctl version 1.80.1

$ kubectl version --short
Client Version: v1.22.7
Server Version: v1.21.9
```

**Comment by eliobischof** [comment]
The CRD missed the `x-kubernetes-preserve-unknown-fields: true` property. The fix is in review

**Comment by F1Feng** [comment]
How about this bug, has it been sloved?

**Comment by F1Feng** [comment]
> The CRD missed the `x-kubernetes-preserve-unknown-fields: true` property. The fix is in review

Cool,  My problem has been solved. Continue to study, Thanks
