### ISSUE TITLE
Translation/Wording phone number

### ISSUE THREAD

**Issue by juergrinaldi** [caos/zitadel#3113]
In Userprofile, Contact Information:

- [x] change 'phonenumber' to 'Phone number'
- [x] change label inputfield 'New Value' to  'Phone number'
- [x] check if there are other translation issues regarding 'phonenumber'

**Comment by juergrinaldi** [comment]
(WIP)

- [ ] phone number
- [ ] label input phone number

**Comment by fgerschwiler** [comment]
estimate <0.5d
