### ISSUE TITLE
Changes empty attributes

### ISSUE THREAD

**Issue by peintnermax** [caos/zitadel#3140]
Ensure changes do not contain empty attributes

<img width="341" alt="Bildschirmfoto 2022-01-31 um 11 08 30" src="https://user-images.githubusercontent.com/10165752/151774866-a6dd57e4-ee7d-4bb4-bf37-82e18a0beb14.png">

**Comment by fgerschwiler** [comment]
We have some changes, where no user is behind. These are system changes. So we will not be able to provide these attributes.

**Comment by peintnermax** [comment]
Does it make sense to return system as editor?

**Comment by peintnermax** [comment]
<img width="210" alt="Bildschirmfoto 2022-01-31 um 11 36 15" src="https://user-images.githubusercontent.com/10165752/151778747-7ad306df-6f33-49cf-a56e-de73d969c30a.png">
sometimes we have names for the changes, sometimes not. Here we have Login as editor

**Comment by fgerschwiler** [comment]
estimate <0.5d
