### ISSUE TITLE
Console: Display Action state

### ISSUE THREAD

**Issue by livio-a** [caos/zitadel#3145]
Actions can now de- and reactivated (https://github.com/caos/zitadel/pull/3143) manually or automatically (features). 

**Acceptance criteria**
- [ ] Users must be able to deactivate and reactivate actions in the actions overview.
- [ ] deactivated actions must be marked if they're (already) use in a flow
- [ ] show how many activate actions are possible

**Comment by fgerschwiler** [comment]
estimated: 1d
