### ISSUE TITLE
Projection handlers create their own tables

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#3146]
Projection handlers reacte to handler events and create their own tables.

**Acceptance criteria**
- [x] Creating tables
- [x] Implemented in all existing handlers

**Comment by fforootd** [comment]
@adlerhurst mentioned [goose](https://github.com/pressly/goose#embedded-sql-migrations) as possible way to integrate the migrations into zitadel

**Comment by fforootd** [comment]
https://github.com/golang-migrate/migrate looks also well maintained

**Comment by livio-a** [comment]
need setup for creation of `locks`, `failed_events` and `current_sequences` table

**Comment by livio-a** [comment]
now adding tenant (columns) for https://github.com/caos/zitadel/issues/3057
