### ISSUE TITLE
Translation reset password flow in German

### ISSUE THREAD

**Issue by sebastianbuechler** [caos/zitadel#3150]
The confirmation button and the description have the same typo in the German version of reset password flow. Also the password checker uses sometimes the English version "password" in the German version:
![image](https://user-images.githubusercontent.com/42775578/152110418-6c6e3465-3c99-4c38-98bb-1559b1c209f1.png)

**Comment by fgerschwiler** [comment]
@sebastianbuechler thanks for your report. We will have a look at this.
