### ISSUE TITLE
NewPasswordConfirmationLabel -> Translation missing

### ISSUE THREAD

**Issue by virth** [caos/zitadel#3152]
**Describe the bug**
«NewPasswordConfirmationLabel» is not translated in english.

**To Reproduce**
1. Create new User
2. Login the first time
3. You will be asked to change password

**Expected behavior**
Should be translated.

**Screenshots**
![image](https://user-images.githubusercontent.com/18188015/152136900-b2f5fba1-ac93-4287-b2f3-280b4edfa6f5.png)

**Comment by fgerschwiler** [comment]
@virth Thanks for your report we will have a look at it

**Comment by fforootd** [comment]
Does this relate to #3150 as well?
