### ISSUE TITLE
Remove metadata from images

### ISSUE THREAD

**Issue by fforootd** [caos/zitadel#3169]
**Describe the bug**
When a user does upload images and logos the metadata exif metadata are not stripped.

**To Reproduce**
1. Upload a testing image with EXIF tags filled.
2. Downloading the image or copying the URL for the same.
3. Using an online tool to view the EXIF data.

**Expected behavior**
Strip exif when uploading.

**Comment by fforootd** [comment]
This issue was reported by an external user.

FYI @livio-a @fgerschwiler

**Comment by fgerschwiler** [comment]
estimate: <0.5d
