### ISSUE TITLE
clarify naming for grants

### ISSUE THREAD

**Issue by adlerhurst** [caos/zitadel#317]
at the moment we have 3 objects `ProjectGrant`, `UserGrant`,`ProjectGrantUserGrant`. In my opinion it's too difficult to understand what these objects and and API-methods.

my proposal is:
* `ProjectGrant` 
  * in zitadel: company (A) buys a project from another company (B). To use this project, company (B) get's a `ProjectGrant` 
  * is okay (dictionary says "agree to give or allow (something requested) to.")  
* `UserGrant` => `UserPermission`/`UserAuthorization`
  * A user gets access to a project of his organisation
  * (dictonary for permission: "the action of officially allowing someone to do a particular thing; consent or authorization.")
* `ProjectGrantUserGrant` => `DelegatedUserPermission`: 
  * A user gets a `UserPermission` for a project thats granted to his company (`ProjectGrant`)
  * Another possibility could be to remove this object and add an optional field to `UserPermission`, because all i want is a Permission for the user.

con for delegation: a team member "delegates" his task to me. So I am his deputy (livio gibt mir "seine" UserPermission damit ich einen Task für ihn erledigen kann.)

**Comment by fgerschwiler** [comment]
@adlerhurst ProjectGrantUserGrant is actually the same as usergrant, its just to check the permissions

**Comment by fgerschwiler** [comment]
#489 with this merge request its possible to only use usergrant, projectusergrant and projectgrantusergrant is deprecated, as soon as usergrant requests are used in frontend we can remove the deprecated requests
