### ISSUE TITLE
ZITADEL works instance based

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#3226]
Instance and host should be handled in all requests, configs, etc. 

**Acceptance criteria**
- [x] Handle cookies on specific host (handle context in cookie handler)
- [x] OpenID Provider should handle host and tenant
- [ ] SAML Provider should handle host and tenant
- [x] handle console redirect url tenant based
- [x] Notifications (Emails) should handle tenant (urls, branding)

**Comment by livio-a** [comment]
IMO we can close this issue and create a separate for SAML when needed
objections @fgerschwiler ?
