### ISSUE TITLE
Encryption keys logic

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#3232]
Encryption key should be handled system wide.

It will be possible to load encryption keys into ZITADEL from different systems (Vault, Google KMS, ...). For start and as default the keys are going to be stored (encrypted by a master key) in the ZITADEL Database on a separate projection and table.

**Acceptance criteria**
- [x] cli init creates projection and table
- [x] key(s) can be generated / provided into DB by cli
- [x] ZITADEL will generate all necessary keys with default keyIDs if table is empty
- [x] ZITADEL loads keys from DB on start (with master key)
- [x] defaults.yml is updated to contain all default keyIDs

**Comment by livio-a** [comment]
estimate: 2d
