### ISSUE TITLE
permissions in global org

### ISSUE THREAD

**Issue by adlerhurst** [caos/zitadel#330]
If I use console with my user in global org i get a "No matching permission found" in a lot of requests. (e.g. Personal Information)
![image](https://user-images.githubusercontent.com/27845747/86327965-649c8a00-bc44-11ea-8c36-1108ca5c6169.png)

**Comment by livio-a** [comment]
@peintnermax told me it's due to reading the policy... we might need to allow reading to `authenticated`

will check with @fgerschwiler

**Comment by fgerschwiler** [comment]
I made a new request getmypolicy
