### ISSUE TITLE
Can't choose different Token (2FA)

### ISSUE THREAD

**Issue by juergrinaldi** [caos/zitadel#3312]
**Describe the bug**
I wanted to login to zitadel and when I chose 'USB Token' and tried my FIDO it didn't recognized it (because it seems I haven't registered it on here). When I want to choose another method, it doesn't let me.
Hitting 'Try again' will just fail again and when choosing 'Close' and 'Validate Token' it will also fall back to this Message:

**Expected behavior**
I want to be able to choose a different 2FA method to validate my identity if one fails.

**Screenshots**
![image](https://user-images.githubusercontent.com/48990649/157629727-dac193c3-9c5b-478b-8314-e9d4746137d6.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome (latest version)

**Comment by fgerschwiler** [comment]
@juergrinaldi We talked about this issue, your problem is in the part of the browser where we can't influence the behaviour. Do to this I will close this issue.
