### ISSUE TITLE
Implement system api

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#3328]
Implement the system api with authentication

**Acceptance criteria**
- [x] Based on the proto of: #3061 
- [x] Start system api
- [x] System api command side
- [x] System api query side
- [ ] Authentication

**Comment by livio-a** [comment]
@fgerschwiler should we create a separate issue for the authentication?

**Comment by fgerschwiler** [comment]
> @fgerschwiler should we create a separate issue for the authentication?

yes I think that would be better

**Comment by livio-a** [comment]
authentication will be solved with https://github.com/caos/zitadel/issues/3466
