### ISSUE TITLE
Testing ZITADEL, 2nd iteration

### ISSUE THREAD

**Issue by thesephirot** [caos/zitadel#333]
- [x] Error Message if user not exists should be "user does not exist", or something similar:

![image](https://user-images.githubusercontent.com/47860090/86374041-66863d80-bc84-11ea-8bf8-727227ff6f49.png)

- [x] Login worked after the 2nd try (no 2fa), the first attempt showed_ (@adlerhurst )
![image](https://user-images.githubusercontent.com/47860090/86374217-9a616300-bc84-11ea-8d9d-90aea50b6285.png)

- [x] after the login, 2 names are shown instead of only one:
<img width="961" alt="Screenshot 2020-07-02 at 16 54 54" src="https://user-images.githubusercontent.com/47860090/86374395-cbda2e80-bc84-11ea-9920-d38e4cf734bc.png">

- [x] when 2  user contexts are  active  and a phone is registered, 2 verification  codes are sent, one is valid.: (@fgerschwiler )

<img width="353" alt="Screenshot 2020-07-03 at 09 29 41" src="https://user-images.githubusercontent.com/47860090/86443865-29678d00-bd10-11ea-899b-8f817d4d03f3.png">

<img width="716" alt="Screenshot 2020-07-03 at 09 29 47" src="https://user-images.githubusercontent.com/47860090/86443908-3ab09980-bd10-11ea-853b-51ba7ffc5a91.png">

- [x] same  regard as above, wouldn`t it make sense to have multiple telephone  numbers available as option? (no because from iam sight we only need one phone, to send you some messages )

- [ ] signed out page does only appear when  the "last user" is logged out. when multiple users are logged in and one is still registered the login page appears  instead. (but no  option in the right corner to switch  to the active one)
<img width="724" alt="Screenshot 2020-07-03 at 09 40 17" src="https://user-images.githubusercontent.com/47860090/86444676-684a1280-bd11-11ea-9d1e-87155efb713a.png">

- [x] saving profile gives resource owner error:
<img width="513" alt="Screenshot 2020-07-03 at 09 42 44" src="https://user-images.githubusercontent.com/47860090/86444897-c24ad800-bd11-11ea-8594-d837717a53ae.png">

- [ ] did a basic login test with cypress, it reports cross site problems:
<img width="1035" alt="Screenshot 2020-07-03 at 10 08 49" src="https://user-images.githubusercontent.com/47860090/86447225-51a5ba80-bd15-11ea-82eb-36400f0b7eea.png">

- [x] it should be  (s)elect managers:
<img width="750" alt="Screenshot 2020-07-03 at 12 28 29" src="https://user-images.githubusercontent.com/47860090/86460510-ce8e5f80-bd28-11ea-9566-e97b88e7cba9.png">

- [x] create member grant does not  give a result  while searching:
<img width="673" alt="Screenshot 2020-07-03 at 12 30 46" src="https://user-images.githubusercontent.com/47860090/86460695-21681700-bd29-11ea-9411-5f25a32da538.png">

- [x] when creating multiple roles at once an error occurs:
<img width="812" alt="Screenshot 2020-07-03 at 12 32 27" src="https://user-images.githubusercontent.com/47860090/86460937-891e6200-bd29-11ea-9db3-61866f74a340.png">
(re did for error message:)
<img width="644" alt="Screenshot 2020-07-03 at 12 36 32" src="https://user-images.githubusercontent.com/47860090/86461184-e2869100-bd29-11ea-96bb-134d20a1f527.png">

  after the error, the first 2 roles out of three are created:
<img width="700" alt="Screenshot 2020-07-03 at 12 35 13" src="https://user-images.githubusercontent.com/47860090/86461033-afdc9880-bd29-11ea-9f98-19651d4b5b9d.png">
when doing the 2nd test, only one role got  created

- [x] when creating an authorization,I pick an email:
<img width="719" alt="Screenshot 2020-07-03 at 12 39 56" src="https://user-images.githubusercontent.com/47860090/86461523-6476ba00-bd2a-11ea-92a1-0795af197ed4.png">
the  next page is empty...correction...  it takes a lot  of time until the  save button appeares:
<img width="1073" alt="Screenshot 2020-07-03 at 12 41 21" src="https://user-images.githubusercontent.com/47860090/86461627-938d2b80-bd2a-11ea-9b3b-6f7587489602.png">

- [x] last change shows "added", but  what has been added ?
<img width="1110" alt="Screenshot 2020-07-03 at 12 42 54" src="https://user-images.githubusercontent.com/47860090/86461785-cafbd800-bd2a-11ea-9187-996fdc819c59.png">

- [x] creating a new application gives error:
<img width="1074" alt="Screenshot 2020-07-03 at 12 49 25" src="https://user-images.githubusercontent.com/47860090/86462318-b835d300-bd2b-11ea-8b93-22c0395613c4.png">

(but it works with this options)
<img width="1021" alt="Screenshot 2020-07-03 at 12 51 13" src="https://user-images.githubusercontent.com/47860090/86462465-f3d09d00-bd2b-11ea-95d5-96056c7b5ee8.png">

- [x] switching from active to inactive gives error:
<img width="913" alt="Screenshot 2020-07-03 at 12 52 34" src="https://user-images.githubusercontent.com/47860090/86462629-2b3f4980-bd2c-11ea-94bc-0f9ff2b84acb.png">
(but duplicates the project : )
<img width="738" alt="Screenshot 2020-07-03 at 12 53 46" src="https://user-images.githubusercontent.com/47860090/86462677-43af6400-bd2c-11ea-8315-15040ad93179.png">

- [x] error messages switch between english and german

- [x] "info" on a project activates the hook,... but no info  is shown (only (de)activate options on top)
<img width="1162" alt="Screenshot 2020-07-03 at 12 56 11" src="https://user-images.githubusercontent.com/47860090/86462883-b587ad80-bd2c-11ea-9213-c82ef7e2e311.png">

**Comment by adlerhurst** [comment]
Screenshot of „unable to create event“ was taken at 2020-07-02 at 16.44.45

**Comment by livio-a** [comment]
loginname issue fixed by https://github.com/caos/zitadel/pull/337

**Comment by livio-a** [comment]
@thesephirot loginnames are correct... will explain to you in office
