### ISSUE TITLE
ListUsers endpoint `sorting_column` does not work

### ISSUE THREAD

**Issue by jdclarke5** [caos/zitadel#3467]
**Describe the bug**
The list of users from the `ListUsers` API endpoint (https://docs.zitadel.ch/docs/apis/proto/management#listusers) seems to return unsorted even after setting the `sorting_column`. We have observed this within the console as well. It makes pagination to find a user near impossible as the order changes every time.

**To Reproduce**
Query the ListUsers endpoint and ask it to sort by e.g. username, as below. Or, go to the console, list all users, and paginate through. Observe that the order changes each time.

**Expected behavior**
It should return sorted, and pagination should then therefor be reliable

**Screenshots**

![](https://user-images.githubusercontent.com/14137523/164593000-ceb33064-e15d-4412-b1a4-1036989818f2.png)

**Additional context**
We are self-hosting Zitadel currently on version `1.82.16`.

**Comment by fgerschwiler** [comment]
Hi @jdclarke5 thanks for your feedback
It looks like we don't handle the sorting column.
We will fix this.

**Comment by jdclarke5** [comment]
Amazing thank you ZITADEL team!
