### ISSUE TITLE
improve org. setup flow

### ISSUE THREAD

**Issue by fforootd** [caos/zitadel#367]
we should improve the flow with the org setup

- create wizard with register flow (TBD)
- send username to user and prompt for password
- the user register flow should also be usable for self-signup of org. users

Frontend:
- [ ] Add create org (only name) (authorized user is org member) for users with create.org
(RegisterOrg in management api)

**Comment by fgerschwiler** [comment]
in my opinion we need to different org set up flows:
1. New Customer needs an organisation,
  - RegisterOrganisation(), CreateOrg, RegisterUser
  - Should this be in admin api? no authorization needed
2. Existing Customer wants to add a second Organisation
  - Create Org with my User as Org Member
  - This should be in management api

**Comment by fforootd** [comment]
## Option 1

> RegisterOrganisation(), CreateOrg, RegisterUser
Should also include the option to verify ones domain.

> Should this be in admin api? no authorization needed
I think we should build a `GUI` analog to the `userRegister`.

> Do we integrate this in zitadel marketing website?
Yes, it should be possible to supply request params to fill the form

## Option 2

> Create Org with my User as Org Member
yes 😁 

> This should be in management api
yes, with AuthN and AuthZ, either with the personal account or a service account

> Who is allowed to do this?
I believe everyone should be allowed to do this, analog to how `gitlab` handles groups

**Comment by fgerschwiler** [comment]
### Option 1
Register Org Form: 
{{loginurl}}/login/register/org?orgname=Caos&username=fabienne

### Option 2
CreateOrgRequest in management API
Authorised user is added as OrgOwner to new Created Organisation
