### ISSUE TITLE
logout breaks frontend on other tab

### ISSUE THREAD

**Issue by buehler** [caos/zitadel#372]
when clicking the "logout all users" button in the right top corner of the app, it correctly signs the user(s) out of the current tab. However, when I refresh on another tab which was logged in, the frontend breaks.

![image](https://user-images.githubusercontent.com/1067213/86808778-76829080-c07b-11ea-8ca6-912b9199f709.png)

**Comment by buehler** [comment]
(I needed to clear cookies / session storage afterwards)

**Comment by peintnermax** [comment]
a toast message with the possibility to sign in again appears now
