### ISSUE TITLE
Header overwrite

### ISSUE THREAD

**Issue by adlerhurst** [caos/zitadel#375]
`2020-07-07T16:02:13.894501434Z 2020/07/07 16:02:13 http: superfluous response.WriteHeader call from github.com/caos/zitadel/internal/api/http/middleware.(*headers).ServeHTTP (security_headers.go:75)`

This log appears very often

**Comment by adlerhurst** [comment]
https://groups.google.com/u/1/g/golang-nuts/c/xsSQuTf_6s4?pli=1

**Comment by livio-a** [comment]
apparently it's a problem in console only... login works perfectly
