### ISSUE TITLE
project roles: cannot create roles

### ISSUE THREAD

**Issue by buehler** [caos/zitadel#385]
If either creating one or multiple roles on a project, the following message appears:

![image](https://user-images.githubusercontent.com/1067213/86884906-a02bce00-c0f4-11ea-8c3d-c48739ff2935.png)

**Comment by buehler** [comment]
![image](https://user-images.githubusercontent.com/1067213/86885033-d8331100-c0f4-11ea-8a95-8a8489f31340.png)

**Comment by fgerschwiler** [comment]
first error i couldn't reproduce, I tried multiple times
second error activity is solved
