### ISSUE TITLE
project roles: after save, view is not updated

### ISSUE THREAD

**Issue by buehler** [caos/zitadel#402]
when creating roles on a project, after clicking save, the role view is not updated correctly:

![project roles](https://user-images.githubusercontent.com/1067213/87002247-78526e00-c1b9-11ea-88e4-9012b85e4116.gif)

**Comment by fgerschwiler** [comment]
zitadel is based on an eventstore, so its possible, that the read models are not up to date,
we include an refresh button on list components, that its possible to reload
