### ISSUE TITLE
Roleconcept

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#447]
IAM-OWNER: all permission
IAM-OWNER-VIEWER: all permissions read
ORG-OWNER: all permissions on ORG
ORG-OWNER_VIEWER: read permissions on ORG
ORG_PROJECT_CREATOR: self permissions, create projects, create authorizations for this project
PROJECT_OWNER: all permissions on PROJECT
PROJECT_OWNER_VIEWER: read permissions on PROJECT
PROJECT_GRANT_OWNER:
PROJECT_GRANT_OWNER_VIEWER:
ORG-USER-PERMISSION-EDITOR: user permissions, everything else as read
ORG-PROJECT-PERMISSION-EDITOR: Project permissions

**Comment by fgerschwiler** [comment]
I tried to define what roles make sense. At the moment we have a lot more, which doesnt make sense in my opinion.
Please review, @adlerhurst @livio-a @fforootd @peintnermax

**Comment by livio-a** [comment]
Looks good... but not sure about naming of `1_LVL_SUPPORTER` and `2	_LVL_SUPPORTER`
