### ISSUE TITLE
[UX] 2FA Setup

### ISSUE THREAD

**Issue by maennchen** [caos/zitadel#452]
* Only ask for user input if there's actually a choice
* Explain the term OTP for dummies in a few words so that people know what it means

![unneeded-mfa](https://user-images.githubusercontent.com/333918/87319686-3d8a6600-c52a-11ea-9f10-3699907d3be6.png)

**Comment by juergrinaldi** [comment]
As mentioned before, I totally agree on this.
I'd suggest to go with a descriptive text and just two buttons as long as there is only one option. (later we can add the radio buttons again)
Something along those lines:
![image](https://user-images.githubusercontent.com/48990649/87394634-53426e80-c5b0-11ea-9619-a8502d90cbab.png)

**Comment by fforootd** [comment]
will be closed in favour of #8
