### ISSUE TITLE
[UX] New Password Validation

### ISSUE THREAD

**Issue by maennchen** [caos/zitadel#453]
Provide Warnings while typing instead of after reload (makes me write two passwords again).

![pw](https://user-images.githubusercontent.com/333918/87319784-6579c980-c52a-11ea-8735-eadcc96737a0.png)

**Comment by juergrinaldi** [comment]
my suggestions:
![image](https://user-images.githubusercontent.com/48990649/87516019-04aed600-c67d-11ea-811a-73292f28381f.png)

Mobile would be like this. (and I tend to prefer the inline-version also for the desktop/widescreen (not on the right side)
![image](https://user-images.githubusercontent.com/48990649/87516038-0b3d4d80-c67d-11ea-9ae6-5a00cc3bc7ea.png)

Variants:
![image](https://user-images.githubusercontent.com/48990649/87516056-11332e80-c67d-11ea-8fc3-3ea3f6f16b57.png)

![image](https://user-images.githubusercontent.com/48990649/87516092-1abc9680-c67d-11ea-8d59-1d4b22798ebb.png)


Please set new signal colors as follows:
Green/OK: `#0DF279`
Red/NOK:  `#F20D6B`
