### ISSUE TITLE
[UX] Only show the Configure OTP button when it can be used

### ISSUE THREAD

**Issue by maennchen** [caos/zitadel#456]
When clicking the `Configure OTP` button and OTP is already set up, the user gets the error message shown in the screenshot.

* The error is not translated
* The button should not be shown if it can't be used
* Why can't I add multiple second factors?

![otp_already_ready](https://user-images.githubusercontent.com/333918/87320577-60694a00-c52b-11ea-9a1c-c4cd2feff2bb.png)

**Comment by fforootd** [comment]
@maennchen do you want to add multiple `OTP` or in general multiple `factors`

**Comment by maennchen** [comment]
@fforootd I wanted to see if I can add other factors like a U2F key. I'm not sure if multiple OTP factors is needed. Multiple factors in general are useful in my opinion though.

**Comment by fforootd** [comment]
Ok yes this is planned, especially, WebAuthN for U2F (CTAP1) and FIDO2 (CTAP2) for `passwordless`.
As well Mobile TAN, and later on there might come an `APP` 😁

**Comment by juergrinaldi** [comment]
just my 2 cents: 
I agree on the comments from @maennchen with the addon of @fforootd (I'd go with multiple factors but not multiple OTPs)
About the OTP button: As long as there's only one 2FA option it can stay (and get removed when set up) but as soon as there are multiple options, I'd advice a short wizard for the setup process and keep an agnostic 'setup 2FA' button.

**Comment by fforootd** [comment]
This is already fixed
