### ISSUE TITLE
[UX] Domain Confirmation

### ISSUE THREAD

**Issue by maennchen** [caos/zitadel#457]
* pressing `Enter` should send the `new domain` form
* After adding, the `verification file` is not visible to be downloaded and the URL to upload it to is also not shown
* (DNS Proofs would probably be easier for most customers)

![new_domain](https://user-images.githubusercontent.com/333918/87320840-bb02a600-c52b-11ea-9e8a-b343aab8aa72.png)

**Comment by fforootd** [comment]
@maennchen the proof has yet to be implemented, but we plan to use more or less the same process `ACME` uses, for now we generate a dummy domain for each domain. This will be used whenever no domain is verified.

- DNS
- HTTP

[ACME Challenge Types](https://letsencrypt.org/docs/challenge-types/)
