### ISSUE TITLE
[Dev UX] Show Issuer Information in App

### ISSUE THREAD

**Issue by maennchen** [caos/zitadel#494]
Show some more information for the developer in the App Detail view:

* Configuration URL
* Issuer URL
* Authorization Endpoint (for people using OAuth 2.0 and not directly OpenID)
* Token Endpoint (for people using OAuth 2.0 and not directly OpenID)
* JWK's URI (for people using the JWKs directly)

**Comment by fforootd** [comment]
This makes absolut sense 😁 

@fgerschwiler @adlerhurst @peintnermax do we need to extend the API for this or should we solve this in the `UI` alone?

I think it would be sufficient to solve this within `console` for now.

**Comment by fgerschwiler** [comment]
@fforootd @peintnermax 

- I added zitadel docs request in management api, in this request you get issuer and discovery endpoint

-  authorize, token, keys endpoint we should get from discovery endpoint

- management, auth and admin endpoints are already configured in console

we should show all of them in console on an application (dev information)

**Comment by fgerschwiler** [comment]
we added issuer and discovery endpoint to the appconfiguration
all other endpoints (managementapi, adminapi, authapi) will be in the docs as soon as we have some

**Comment by fforootd** [comment]
This is documented and also shown in the gui

We will however improve things again in the close future

**Comment by fforootd** [comment]
[OIDC Docs for ZITADEL](https://docs.zitadel.ch/documentation#Endpoints_and_Domains)
