### ISSUE TITLE
[Dev UX] Provide Better Errors with wrong config

### ISSUE THREAD

**Issue by maennchen** [caos/zitadel#495]
When an app is misconfigured, the error should be better. (Error Example: Initiate Login with wrong RedirectURI)

The error page should solve two things:

* Tell a developer what he did wrong and how / where to fix it
* If for some reason a user ever reaches the site, it should tell him to contact the administrator of the application.

![dev_error](https://user-images.githubusercontent.com/333918/88073875-faa63f00-cb76-11ea-84d1-11a4d9253796.png)

**Comment by JCustin** [comment]
Hello,

I'd love to help you out. Where can I find the find the files for the current error message?

**Comment by fforootd** [comment]
Hi @JCustin, sorry for not having clear guides, **yet** 😁 

Our `OpenID Connect` errors are located within our OIDC lib for `Go`.

Of the top of my head i would say the errors are not yet placed in a nice dictionary file.
I think the code is located https://github.com/caos/oidc/blob/master/pkg/op/authrequest.go#L90

**Comment by fgerschwiler** [comment]
- On the app configuration we show if the client is compliant and if not, why it isnt.
- Error messages improved
