### ISSUE TITLE
[UX] Login / Select Account Design

### ISSUE THREAD

**Issue by maennchen** [caos/zitadel#496]
The green point looks out of place in the user selection.

![choose_account](https://user-images.githubusercontent.com/333918/88074133-507ae700-cb77-11ea-858a-5fa5e55b7d0e.png)

**Comment by maennchen** [comment]
(Especially when the user is not hovered...)

**Comment by fforootd** [comment]
Incoming changes #491

**Comment by fforootd** [comment]
This will be fixed as soon as 0.61.3 makes it to the `.ch`

<img width="1344" alt="Screenshot 2020-07-22 at 11 59 40" src="https://user-images.githubusercontent.com/9879976/88163370-da2bc280-cc12-11ea-8097-453e92129efd.png">
