### ISSUE TITLE
Redirect URI not allowed when using Implicit Auth

### ISSUE THREAD

**Issue by maennchen** [caos/zitadel#499]
The same application with the same urls and client can successfully login via `response_type` `code`, but when using `token id_token` instead, the error `redirect_uri not allowed` is shown.

Expected: Login works

**Comment by fforootd** [comment]
Can you please provide a example `redirect URI`?
I think this has to do with the fact that the spec. prohibits the use of `non https redirect uri` with implicit flows in `non native clients`

[OpenID Connect Core 1.0 incorporating errata set 1](https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest)

```md
REQUIRED. Redirection URI to which the response will be sent. This URI MUST exactly match one of the Redirection URI 
values for the Client pre-registered at the OpenID Provider, with the matching performed as described in Section 6.2.1 of 
[RFC3986] (Simple String Comparison). When using this flow, the Redirection URI MUST NOT use the http scheme unless the 
Client is a native application, in which case it MAY use the http: scheme with localhost as the hostname.
```

With #490 this will be improved

**Comment by maennchen** [comment]
@fforootd I used `http://localhost:8080/oidc-callback`.

**Comment by fforootd** [comment]
Ok, and your `app type` was `web` i guess. Because in this case it is correct to fail.

With #490 there will be a `dev mode` to explicitly violate the spec. for testing 😁

**Comment by maennchen** [comment]
@fforootd Yes, seems to be correct then. Seems like every OIDC provider I've worked with violated this rule.

The error message should be better to explain this exact problem then.

(Maybe even the App Edit Form should provide some kind of warning if incompliant redirect urls are entered for the selected app type / grant type.)

**Comment by fforootd** [comment]
This change is incoming:

![image](https://user-images.githubusercontent.com/9879976/88152884-f4f73a80-cc04-11ea-8a84-44bafc3bdfdc.png)

**Comment by fgerschwiler** [comment]
- its now possible to set dev mode on an application, in this case redirect uris are not validated
