### ISSUE TITLE
Domain Verification Feature

### ISSUE THREAD

**Issue by fforootd** [caos/zitadel#5]
## Use Case
As customer I want to verify my own domain.

- Root domain verification e.g caos.ch
- Sub domain verification e.g sub.caos.ch

## Implementation
- #123

## Polices
- Billing #122
- Username usage #117 

## Additional Impacts
- We need to have some kind of migration process available to users already created in the global org. see here -> #7

**Comment by fgerschwiler** [comment]
This is already implemented
