### ISSUE TITLE
[Feature] Provide Client Grant

### ISSUE THREAD

**Issue by maennchen** [caos/zitadel#500]
Support Client Grant

**Comment by fforootd** [comment]
The `client credential grant` is already supported. See below the snippet from the discovery document

```json
  "grant_types_supported": [
    "client_credentials",
    "authorization_code",
    "urn:ietf:params:oauth:grant-type:token-exchange"
```

However i think you are missing `service accounts` which is WIP here #470. Is my guess correct 😁 ?

**Comment by maennchen** [comment]
@fforootd Woudn't they be listed here if they were supported?

![grant_types](https://user-images.githubusercontent.com/333918/88151723-53231e00-cc03-11ea-840c-1c0405b5c256.png)

**Comment by fforootd** [comment]
Not necessarily, because the `client credential grant` is not a `OpenID Client/Application` but instead a `service account` which uses `OAuth 2. 0` to get a `access_token`.

**Comment by maennchen** [comment]
@fforootd Then I would think about the naming. 

The [RFC](https://tools.ietf.org/html/rfc6749#section-4.4) mentions client credentials as `Client Credentials Grant`. 

Based on that I assumed that the selection with three entries is all zitadel offers.

**Comment by fforootd** [comment]
That's a fair point, we will see how we can improve naming with this to avoid confusion.

👍

**Comment by maennchen** [comment]
(It would also be good if the client credential grant could be disabled / enabled on an client basis. I would think about just adding client credentials to the selection...)

**Comment by fforootd** [comment]
Hm, a`OIDC Application` will not use the `client credential grant` but `OAuth 2.0 Clients` will. We think of those as `Service Accounts` and not as clients. So there is IMO no need to have a `disable / enable` feature with the OIDC Client.  

But i will discuss this with @livio-a after his holidays 😄. There is much room for `confusion`!

I think improving the UX and docs should solve this problem

**Comment by livio-a** [comment]
realtes to https://github.com/caos/oidc/pull/67
