### ISSUE TITLE
User Creation Improvement / Bug

### ISSUE THREAD

**Issue by fforootd** [caos/zitadel#506]
## Translation is Missing in DE and EN

<img width="901" alt="Screenshot 2020-07-22 at 14 59 34" src="https://user-images.githubusercontent.com/9879976/88179570-6a2a3600-cc2c-11ea-95c1-e99039d0a541.png">

## Save Action should have a spinner to signal the user, that something is working
Right now the page just waits until the save is done.

## Error after successful saving a user

<img width="665" alt="Screenshot 2020-07-22 at 15 01 51" src="https://user-images.githubusercontent.com/9879976/88179676-8ded7c00-cc2c-11ea-9d72-d8e7ff915e48.png">

**Comment by fgerschwiler** [comment]
reread of missing events didnt work if user is not in readmodel
