### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by fgerschwiler** [caos/zitadel#63]
use auth command side directly (must not use grpc)

- [x] Register
- [x] Check Username
- [x] Check Password
- [x] Check OTP
- [x] Setup OTP
- [x] Initial PW
- [x] Init Verify
- [x] Resend Init Code
- [x] Email Verify
- [x] Resend Email Code

**Comment by juergrinaldi** [comment]
Ich haue hier einfach mal meine Findings rein bezüglich Zitadel-Login. Falls etwas nicht ganz klar sein sollte, resp. ich es genauer ausführen soll, einfach melden. Können auch kurz das ganze zusammen besprechen.
Ich bin mal relativ grob drüber sind aber doch einige Sachen aufgetaucht. Wenn wir den Satz behoben haben, kann ich ja sonst dann nochmal genauer drüber, sonst wird es ev. etwas viel, denke ich.

- [ ] urlname '_/username_' bei Registrierung? Hier wäre mMn _'/register'_ sinnvoller.
- [ ] Gender notwendig?
  - [ ] falls Gender notwendig nicht limitiert auf Auswahl (heutzutage kritisch)
- [ ] Nickname nötig? Für was verwendet?
- [ ] Highlighting Focus (beschreiben wie)
- [ ] kein Highlighting Focus bei Button				
- [ ] Bei Login: Username? Ist das der Nickname? Falls ja, unbedingt gleich beschreiben.
- [ ] wenn ich bei E-Mail-Verification bin komme ich ohne Code nie mehr weg. (z.b. registrierung neu anfangen)
- [ ] keine Meldung wenn Passwort nicht ausgefüllt wird
- [ ] kennzeichnung bei nicht ausgefüllten Feldern (Name z.B.) zu schwach (rot hervorheben)
- [ ] Pflichtfelder/Optionals hervorheben. (tendiere zu letzterem, je nachdem von was es mehr gibt)
- [ ] Register new Account als Textlink, nicht secondary
- [ ] Verificaiton Code? Für was? (in Email gibts ja nur Link zur Freischaltung)
- [ ] Multifactor: Beschreibungstexte fehlen
- [ ] Multifactor: ist diese "Doppeleingabe" des Codes wirklich nötig? Find ich etwas unsinnig als Anwender. Ausserdem auch nicht ganz klar ob der alte Code noch gültig ist oder ob ein neuer dafür kommen sollte
- [ ] Passwort forgot ist missleading. Entweder muss da 'Passwort reset' stehen oder ich muss auf eine weitere Seite geleitet werden wo ich den Button 'zurücksetzen' drücke.
- [ ] Den Google Authenticator finde ich total seltsam. a) kriegt man keine Push und b) wird auch noch der bestehende Code überschrieben und nicht mal mit 'ungelesen' markiert. Ausserdem scheint auch nicht der 'aktuellste' Code nach oben geschoben. Das ist absolut nicht benutzerfreundlich. Liegt wahrscheinlich nicht an uns das zu ändern aber find den Mist. :-)
- [ ] wenn ich die Email-Verification auslöse kriege ich ein neues Window im Standardbrowser, nicht dem den ich aktuelle offen habe mit dem Registrierungsprozess. An diesem bleibe ich dann "hängen". Ist etwas unschön.
- [ ] Skip (bei Multifactor reg.) als Textlink, nicht secondary
- [ ] Ich bin grundsätzlich kein Fan von Passwort-requirements aber ich denke eine mindestlänge sollten wir schon abfragen, nicht? ich konnte ein passwort mit 1 zeichen eingeben.

- [ ] Inputs nicht gestyled (siehe Screens, 50px height, border #595959, fill: #252525, rounded corners,... )
- [ ] falsches Blau für Keycolor: (#364DF6)
- [ ] max-width inputs: 500px 
- [ ] Farbe Labeltext: #898989
- [ ] Label im Input weglassen (wiederholt sich nur)
- [ ] height dropdowns
- [ ] padding left inputs (siehe Screens)
- [ ] margin-bottom viiiiel mehr (mind. 50px, ev. 200px damit der Background nie überlappt mit inputs?)
- [ ] 30px margin Logo



(notes to myself) (ist mehr für mich als etwaige Gedankenstütze ;))
- [ ] ev. Schrift auf Montserrat wechseln?
- [ ] ev. doch auf 'Box'-Layout wechseln? (#ihavedoubts #haha)

**Comment by juergrinaldi** [comment]
![image](https://user-images.githubusercontent.com/48990649/80595383-f01b5400-8a24-11ea-8831-edbc1dd78e24.png)
