### ISSUE TITLE
panic if setup not done

### ISSUE THREAD

**Issue by adlerhurst** [caos/zitadel#673]
Zitadel should panic if setup is not executed

**Comment by livio-a** [comment]
readiness probe will fail until setup is done. so no traffic will be directed to pod

btw operator is checking readiness probe

**Comment by adlerhurst** [comment]
Okay. Then at least a log message would help. If somebody starts zitadel locally who doesnt know about startup should get informed in my opinion

**Comment by livio-a** [comment]
well this would be helpful

IMHO ˋgetting startedˋ in docs will have a local section and solve this problem
