### ISSUE TITLE
Improve Eventhandling

### ISSUE THREAD

**Issue by adlerhurst** [caos/zitadel#680]
The following aspects should be improved:

- [ ] Testing view handlers and command side inserts
- [x] simplify aggregate/event creation
- [ ] (backwards compatibility with current solution)
- [x] simplify eventstore push
- [ ] simplify event reading (mapping from eventstore event to object event)
- [x] Backwards compatibility of event handlers (e.g. users)

**Comment by adlerhurst** [comment]
@livio-a @fgerschwiler please add aspects we should have a look at while proposing new event pattern

**Comment by adlerhurst** [comment]
https://go2goplay.golang.org/p/y1SD4XtypBh

**Comment by fgerschwiler** [comment]
- [ ] Project Command Side
- [ ] Migrate unique events to unique table
- [ ] Authrequest with Command Side
- [ ] Some missing requests for Login
- [ ] How to handle big readmodels on command side
- [ ] merge master (command side customm email text)
- [ ] Tests

**Comment by adlerhurst** [comment]
migrate aggregates to single resource owner. at the moment IAM for example could have multiple resource_owners:
`select aggregate_type, aggregate_id, count(resource_owner) as resource_owner_count from (select aggregate_type, aggregate_id, resource_owner from events group by aggregate_type, aggregate_id, resource_owner) group by aggregate_id, aggregate_type having count(resource_owner) > 1;`
