### ISSUE TITLE
Username uniqueness check is global and not per tenant or organization 

### ISSUE THREAD

**Issue by bufferoverflow** [caos/zitadel#724]
**Describe the bug**

error message `user is already user.username.reserved`

**To Reproduce**

Within https://console.zitadel.ch/users/list/humans create a user with Username max or roger. 

**Expected behavior**
Each tenant should have it's own max or roger as username.

**Comment by fforootd** [comment]
Good morning 

Thank you for testing zitadel 👍 

Each org. has their own unique pool of usernames suffixed with the domain name, either verified or generated by zitadel.
For example in the org. caos I do have the username florian, this results in the generated logonname florian@caos-ag.zitadel.ch (generated) and florian@caos.ch (verified). Within caos-ag there can only exist one florian.

So you should be able to have a max and roger in your org.
If it is ok for you I could quickly try to reproduce the error by creating the account max in your org. Roger already exists.

One thing that we are aware of, is that we need to improve our handling of the eventual consistency with the CQRS Readmodels! So it sometime can be that the list renderd in the Console is not updated but the user is properly stored in the Evenstore.

**Comment by bufferoverflow** [comment]
Thank you @fforootd , here is the screenshot.

<img width="619" alt="Screenshot 2020-09-11 at 09 42 09" src="https://user-images.githubusercontent.com/378909/92885614-35a84e80-f413-11ea-9e10-645587f05f24.png">

Anyway this is not that important, just something I recognized.

**Comment by bufferoverflow** [comment]
@fforootd and of course feel free to investigate within my tenant

**Comment by fforootd** [comment]
@bufferoverflow thanks we will do 👍 

@livio-a @fgerschwiler @adlerhurst any clues?

**Comment by fforootd** [comment]
btw. I can reproduce this with my own org.

**Comment by bufferoverflow** [comment]
@fforootd @adlerhurst @fgerschwiler Thanks a lot!

**Comment by fforootd** [comment]
This should be soon deployed :-) keep you posted

Florian Forster

H e a d   o f C A O S

Phone:  +41 79 956 39 01

Web:      www.caos.ch

**Comment by adlerhurst** [comment]
hi @bufferoverflow 

You should now be able to create a max in your organisation. 

Thanks for your report and enjoy your weekend.
