### ISSUE TITLE
Prepare Demo Cluster and application including Zitadel and an Argo CD application for demo purpose

### ISSUE THREAD

**Issue by thesephirot** [caos/zitadel#746]
we need a demo facility to be able to showcase orbos, zitadel and the gitops behavior of argocd.

the cluster shall only run on "demo days"

**Comment by thesephirot** [comment]
we already have a demo repository to showcase a page jürg made once

https://github.com/caos/demo

**Comment by fforootd** [comment]
this was achieved with zitadel.io
