### ISSUE TITLE
Enable Telegram as MFA Type

### ISSUE THREAD

**Issue by MatiMax** [caos/zitadel#749]
Having used __Telegram__ as MFA for a very long time now in another IAM I appreciate both the simplicity and versatility of this type.

It works seamless across wearable, mobile and desktop devices, and — most importantly for me — I have no issues using the _same_ Telegram channel on _any_ device to confirm the log-in. This is in contrast to the OTP MFA type using e.g. Google's Authenticator app which only works on one registered and authorised device.

As long as ZITADEL only supports one MFA of the same type I'd very strongly support the implementation of Telegram.

**Comment by fforootd** [comment]
We don't see a need for this right now.
