### ISSUE TITLE
Project Roles Assertion

### ISSUE THREAD

**Issue by fforootd** [caos/zitadel#766]
## First Party Role / Scope handling
This means requesting project_roles from the project where your client belongs to.

### Project

- [x] Authorisation Check option (Check if the user at least has one role granted)
- [x] Enable Project_Role Assertion (if this is enabled assert project_roles, with the config of the corresponding client)

### Client

- [x] Token Type (JWT or Bearer)
- [x] Assert Project_Roles to id_token
- [x] Assert Project_Roles to access_token

### Scope

If `Enable Project_Role Assertion` is:
**not active** -> a RP can still request a role to be asserted by utilising this scope
**active** -> a RP only will receive the requested scope if available

The scope structure is as follows: `urn:zitadel:iam:org:project:role:{rolename}`

### Claim

The asserted claim is the role with a list of all organisations with granted access rights.

```JSON
{"urn:zitadel:iam:org:project:roles": [ {"user": [ "primarydomain.1", "primarydomain.2" ] } ]}
```

## Third Party Role / Scope handling
This will be available later on see #765

**Comment by fforootd** [comment]
@livio-a instead of **id** we should use **primarydomain** as mean of identifying orgs.

The **id** can not be interpreted by RP's

**Comment by fforootd** [comment]
Btw. i thin the scope `urn:zitadel:iam:org:project:role:{rolename}` is better

**Comment by livio-a** [comment]
@fforootd i see the benefit of using the **primarydomain** for identification (easier readable and rememberable)
but it might change and doing so will break RPs who won't recognise the org anymore

we might offer both at the same time:
```
 "urn:zitadel:iam:org:project:roles": {
    "user": {
      "id1": "primarydomain.1",
      "id2": "primarydomain.2",
    }
  }
```

**Comment by livio-a** [comment]
@fforootd as just discussed this would mean we'll have something like:
```
 "urn:zitadel:iam:org:project:roles": {
    "user": [
      {
         "id": "id1",
         "primaryDomain": "primarydomain.1"
      },
      {
         "id": "id2",
         "primaryDomain": "primarydomain.2"
      }
    ]
  }
```

**Comment by fforootd** [comment]
@livio-a well, if I see it like this, I think the list is less verbose 😁 

```JSON
"urn:zitadel:iam:org:project:roles": {
    "user": {
      "id1": "primarydomain.1",
      "id2": "primarydomain.2",
    }
  }
```
