### ISSUE TITLE
Font is missing unicode ligatures

### ISSUE THREAD

**Issue by maennchen** [caos/zitadel#906]
**Describe the bug**

When using special characters like accents, the font does not have the required ligatures.

**To Reproduce**
1. Register with a name containing accents etc.

**Expected behavior**
A nice rendering of the name

**Screenshots**
![Screenshot from 2020-10-26 13-20-51](https://user-images.githubusercontent.com/333918/97171914-1fb5d980-1786-11eb-9f59-2011039a08ac.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 82.0

**Additional context**

**Comment by fgerschwiler** [comment]
Has been solved a while ago.
