### ISSUE TITLE
SCIM 2.0 Support as client and server

### ISSUE THREAD

**Issue by fforootd** [caos/zitadel#919]
At some point we should provide a SCIM 2.0 client and server Addon

We could reuse existing projects like https://github.com/elimity-com/scim

**Comment by gedw99** [comment]
i was also wondering the same.

https://github.com/elimity-com/scim looks reasonable from first looks at it.

**Comment by fforootd** [comment]
Yeah, we did not yet deeply inspect the project but it could be that we integrate something like this in the future.
