### ISSUE TITLE
[DEV UX] API Documentation

### ISSUE THREAD

**Issue by maennchen** [caos/zitadel#952]
**Is your feature request related to a problem? Please describe.**

Currently the `.proto` have almost no documentation. This leads to very badly documented generated client libraries.

**Describe the solution you'd like**

Add some comments to at least all the RPC Calls.

**Describe alternatives you've considered**

None

**Additional context**

Example of generated docs: https://hexdocs.pm/zitadel_api/api-reference.html
Related Issue in Elixir Client Library: https://github.com/jshmrtn/zitadel_api/issues/1

**Comment by fgerschwiler** [comment]
We added a description for all our requests.
In our api docs we added also the validation to the field description: https://docs.zitadel.ch/docs/apis/introduction
